### ISSUE TITLE
Enhancing Footer

### ISSUE THREAD

**Issue by Bhum-ika** [samyakmaitre/eventmint#100]
The whole footer is designed beautifully but the way links to other pages are added can be improved. it is degrading the whole section.   Also, they should no be aligned in center but in left.

I will add properties to improve this link text and align to the whole UI.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
![image](https://github.com/user-attachments/assets/369c343f-6389-49b3-8d4f-1fa1565207ac)

**Comment by samyakmaitre** [comment]
Go ahead.

**Comment by Bhum-ika** [comment]
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by samyakmaitre** [comment]
Once the issue is resolved I will add DW.

**Comment by Bhum-ika** [comment]
Hey, there is a minor issue
Somebody has imported MovieList in App. js and rendering the same but that component actual name is EventList.
So I am changing the Component name from EventList to Movielist If its okay with you

**Comment by Bhum-ika** [comment]
Hey @samyakmaitre 
I am witnessing this project. Is it correct, quite different from what is deployed.
![image](https://github.com/user-attachments/assets/cb6834f8-5b83-4948-9c2c-b6c5b1522e66)

or you are expecting exact replica of that only

**Comment by Bhum-ika** [comment]
@samyakmaitre Please reply

**Comment by Bhum-ika** [comment]
@samyakmaitre Create PR for what issue?
