### ISSUE TITLE
No Mobile responsiveness

### ISSUE THREAD

**Issue by Sawan-Kushwah** [samyakmaitre/eventmint#105]
![Screenshot_20241007_173047](https://github.com/user-attachments/assets/9fda2f8b-240a-457b-b78b-ec52d95c539b)
See home page is not responsive
Assign me I want to work on this

**Comment by Akanshaku** [comment]
I want to work on this issue by making it responsive on all the devices pls assign me this @samyakmaitre

**Comment by samyakmaitre** [comment]
Please go ahead and create PR.
