### ISSUE TITLE
Bug: I have seen in the signup page the show password icon is not aligned properly.

### ISSUE THREAD

**Issue by tarunkumar2005** [samyakmaitre/eventmint#108]
Bug: I have seen in the signup page the show password icon is not aligned properly.

![image](https://github.com/user-attachments/assets/400e8462-cacc-4de9-ae77-ce807e01ab11)

I want to fix this so assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by Akanshaku** [comment]
I would like to work on this issue by aligning the show password icon on the signup page @samyakmaitre

**Comment by samyakmaitre** [comment]
issue resolved already by another PR
