### ISSUE TITLE
Fix Navbar "Sign In" Button Alignment

### ISSUE THREAD

**Issue by Sharmaji513** [samyakmaitre/eventmint#11]
**Description**
The "Sign In" button on the navbar is not correctly aligned, causing a layout issue. The button should be aligned to the right side of the navbar. The issue might be due to missing or incorrect CSS styling.

**Steps to Reproduce**
Go to the application.
Observe the "Sign In" button on the navbar.
Notice the alignment issue, where the button is not placed correctly on the right.

**Expected Behavior**
The "Sign In" button should be aligned to the right side of the navbar, maintaining uniform spacing and alignment with other navbar items.

**Actual Behavior**
The "Sign In" button appears misplaced and not correctly aligned.

**Suggested Solution**
Use margin-left: auto; or ml-auto in Tailwind CSS.
Verify the structure of the navbar and apply Flexbox or Grid styles if necessary.
Ensure consistent styling with other navbar items.

Screenshots

![2024-10-01-20-50-50](https://github.com/user-attachments/assets/7bda9659-061a-4f8c-bc70-f0a3c3a26cb0)

**Comment by iamsaura8h** [comment]
@samyakmaitre  assign me this issue plz i can start working on it right away

**Comment by rounakdey6** [comment]
level this issue , gssoc , i want to work on it , please assign this issue to me

**Comment by samyakmaitre** [comment]
Issue Resolved by another merge request.
