### ISSUE TITLE
Cgande UI of login and signup page

### ISSUE THREAD

**Issue by MoinVinchhi** [samyakmaitre/eventmint#111]
In login and signup page, images are blurred and displayed with white background which looks unprofessional so I will try to make UI more attractive.

CURRENT UI
![image](https://github.com/user-attachments/assets/15015eca-5f20-4c45-8d39-1c4d227b3518)
![image](https://github.com/user-attachments/assets/bf5a6be2-b1a4-4cd2-9b18-58e0164ffbfc)

**Comment by MoinVinchhi** [comment]
can you please assign this task to me under Hacktoberfest'24

**Comment by samyakmaitre** [comment]
Changes already made under past PR.
