### ISSUE TITLE
Change of Social Media Icons

### ISSUE THREAD

**Issue by anmol-284** [samyakmaitre/eventmint#112]
I can make the social media icons more fascinating and uniquely animated.
just like these........

https://github.com/user-attachments/assets/fe315b92-cc09-44f5-b345-f9a8e20c992d

![Screenshot 2024-10-07 213301](https://github.com/user-attachments/assets/31c1b09c-5439-4213-9ce9-f1def92da19a)

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @samyakmaitre

**Comment by samyakmaitre** [comment]
unable to get the change
