### ISSUE TITLE
Google Authentication using Firebase

### ISSUE THREAD

**Issue by samriddhitiwary** [samyakmaitre/eventmint#116]
I would like to implement Google authentication using Firebase. This feature would allow users to log in quickly and securely using their Google accounts, streamlining the authentication process and improving user experience. It can also enhance security by relying on Google’s authentication infrastructure, which is well-established and trusted.

![image](https://github.com/user-attachments/assets/a538916b-6d98-4e50-91e1-486b3a633cef)

**Comment by samriddhitiwary** [comment]
@samyakmaitre could you please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by samyakmaitre** [comment]
Please go ahead

**Comment by samriddhitiwary** [comment]
@samyakmaitre Thank you I will start working on it

**Comment by samriddhitiwary** [comment]
@samyakmaitre Could you also please assign this also

![image](https://github.com/user-attachments/assets/72145e91-3c72-4e7c-95aa-30b635872c04)

**Comment by samriddhitiwary** [comment]
@samyakmaitre ??
