### ISSUE TITLE
Integrate Calendar Functionality for Event Registrations

### ISSUE THREAD

**Issue by Annanyatiwary4** [samyakmaitre/eventmint#117]
To improve user convenience, I propose adding functionality that allows users to add events to their personal calendars, such as Google Calendar . This feature will enable users to easily keep track of registered events and receive reminders.

i want to work on it.
@samyakmaitre  can you assign me this issue under Gssoc extend and hacktoberfest 2024?

**Comment by samyakmaitre** [comment]
Please go ahead and create PR.

**Comment by Annanyatiwary4** [comment]
Ok, can you label it accordingly?
