### ISSUE TITLE
Add Hover Effect in the Cards

### ISSUE THREAD

**Issue by rupeshv2121** [samyakmaitre/eventmint#120]
![Hover effect](https://github.com/user-attachments/assets/537d6ffd-15ba-4e71-9f4d-7e53c41d29eb)

 Pls assign me under the label gssoc-ext , hactoberfest-accepted

**Comment by rupeshv2121** [comment]
@samyakmaitre sir pls assign me

**Comment by samyakmaitre** [comment]
Please go ahead and create PR. @rupeshv2121
