### ISSUE TITLE
#enhanced interactivity on website

### ISSUE THREAD

**Issue by Varchasavkr** [samyakmaitre/eventmint#122]
previous 

https://github.com/user-attachments/assets/6682f024-8190-489a-ba6f-5af7e503bd02

New 

https://github.com/user-attachments/assets/6ddc545a-b6e8-48a1-9667-8abd03b7529e

Kindly merge this under hacktoberfest-accepted and gssoc-ext and level

thankyou

**Comment by Akanshaku** [comment]
I would like to work on this issue and make the website look more enhanced and interactive assign me this @samyakmaitre

**Comment by Varchasavkr** [comment]
@Akanshaku it has already been solved in pr #123
@samyakmaitre kindly review and mege it

**Comment by samyakmaitre** [comment]
merged.
