### ISSUE TITLE
Component overlap

### ISSUE THREAD

**Issue by shwetharavindrabaliga** [samyakmaitre/eventmint#127]
![image](https://github.com/user-attachments/assets/e11fab9a-88d4-4cb9-94de-8743b55be6d5)
As can be seen from the screenshot, the content on the website overlaps and degrades the UI of the website. I'd like to fix that issue. 
Please assign me @samyakmaitre

 I'd like to contribute.

**Comment by samyakmaitre** [comment]
Please go ahead and create PR, I will add labels
