### ISSUE TITLE
Bug in responsiveness

### ISSUE THREAD

**Issue by Sourabh782** [samyakmaitre/eventmint#131]
![Screenshot 2024-10-08 200303](https://github.com/user-attachments/assets/0f9291e5-cf09-4e58-aee2-15073f022c1e)

Would like to resolve it

**Comment by codergirlprerna** [comment]
@Samyak Matire I want to  improve responsiveness of this project please assign this project to me

**Comment by samyakmaitre** [comment]
Hi @Sourabh782  and @codergirlprerna ,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Don't Forget to connect on Github...

Best regards,
Samyak
