### ISSUE TITLE
adding chatbot

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [samyakmaitre/eventmint#133]
ill add a chatbot which will be tuned to the websites needs.
@samyakmaitre can you please assign me this task.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak
