### ISSUE TITLE
adding dark mode

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [samyakmaitre/eventmint#134]
i can make a good dark mode feature for this ,
@samyakmaitre can you please assign me this task.

**Comment by ayush-343** [comment]
I would like to add light and dark mode feature in this website. So that users can switch mode according to their preferences.
@samyakmaitre can you please assign me this .

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak
