### ISSUE TITLE
[BUG] the top bar doesn't adjust properly in the mobile 

### ISSUE THREAD

**Issue by ayush-343** [samyakmaitre/eventmint#135]
causing it to cramp and thus the search bar to disappear .
 
<img width="365" alt="Screenshot 2024-10-08 at 9 20 19 PM" src="https://github.com/user-attachments/assets/89c6c6f0-54c5-4dcc-8df2-478a64ac625f">
Please assign me this issue  @samyakmaitre  .

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak
