### ISSUE TITLE
Search Bar is not Working Additionally adding 404 not found page

### ISSUE THREAD

**Issue by sid040703** [samyakmaitre/eventmint#137]
if any movie is not found then we can add 404 not found page

Please assign me the task and please include the level and the hactoberfest label

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak
