### ISSUE TITLE
[BUG]: This names of the movie and in poster are different

### ISSUE THREAD

**Issue by Yashwanth112004** [samyakmaitre/eventmint#138]
Poster and movie names does not match at all. 
And posters are repeated. 
![image](https://github.com/user-attachments/assets/8fbbe06e-3e61-468f-9d5a-6d094b57b070)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak

**Comment by Yashwanth112004** [comment]
Will I get any PRs for solving this Issue in GSsoc
