### ISSUE TITLE
Fixing navbar to the top while scrolling

### ISSUE THREAD

**Issue by Sourabh782** [samyakmaitre/eventmint#14]
Fixing navbar to the top of screen while scrolling to improve navigation
![Screenshot 2024-10-01 213705](https://github.com/user-attachments/assets/c789216c-5449-46d6-9555-a3049155cfed)

**Comment by annuprajapati3** [comment]
I can fix it , assign me this .

**Comment by Sourabh782** [comment]
@annuprajapati3 bro according to guidelines, the issue is assigned to the one who raised the issue, if u see someone not working since a week, then u can ask for reassignment

**Comment by Sourabh782** [comment]
@samyakmaitre can you assign me this issue?

**Comment by samyakmaitre** [comment]
issue resolved already by another PR
