### ISSUE TITLE
Add customized favicon 

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#140]
![image](https://github.com/user-attachments/assets/c3e8e996-6461-4066-8792-bf6f9feebaa5)

i want to add a favicon for the website 
please assign this issue to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak

**Comment by AyushSharma72** [comment]
> Hi there, Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....
> 
> Best regards, Samyak

then why did you close the issue ?? @samyakmaitre
