### ISSUE TITLE
Google Login Does Not Display User Profile

### ISSUE THREAD

**Issue by itbindu** [samyakmaitre/eventmint#141]
After successfully logging in or registering using Google, the application does not display the user profile as expected. Instead, the profile section remains blank or does not appear at all. This issue affects user experience, as users cannot access their profile information after logging in.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak

**Comment by itbindu** [comment]
okk
