### ISSUE TITLE
Twitter logo wrong . Already Changed accept PR

### ISSUE THREAD

**Issue by vedhcet-07** [samyakmaitre/eventmint#143]
Sir i saw that twitter logo was wrong . i changed it also . i request you to please accept pr . please assign this to me under gssoc and hacktoberfest . Thank you sir . Let me know if any changes

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak
