### ISSUE TITLE
add brand app colors on hovering the icons in the footer

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [samyakmaitre/eventmint#145]
<img width="312" alt="image" src="https://github.com/user-attachments/assets/269b6ae6-a49f-4164-a313-79bc923e4bbb">
add brand app colors on hovering the icons in the footer

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
i would like to work on it

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
the issue is closed sir
