### ISSUE TITLE
facing issues in sign in , search bar, booking, navbar 

### ISSUE THREAD

**Issue by urvi1622005** [samyakmaitre/eventmint#148]
Hii i am urvashi
I am facing following issue :-
1-After sign in there is no profile section a persons picture should be there also there is no sign up button 
2-search bar is not working 
3-navbar is not looking crazy i think framer motion should be apply there 
4- I have a question if a person does not want to book a show  in such cites which are mentioned in my point of view more cites should be listed
5-ticked booking not working 

screenshots
![Screenshot (313)](https://github.com/user-attachments/assets/df5d8fbe-ecdb-4e6f-a7cd-9b3144bda52e)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak
