### ISSUE TITLE
feat : Improving navbar with proper  alignment and content

### ISSUE THREAD

**Issue by laxmanp090404** [samyakmaitre/eventmint#15]
![image](https://github.com/user-attachments/assets/5a1c4aa2-7816-462f-98cc-c9d7d7d51bbe)
As seen in the above image the **Sign in text is wrapping**  affecting the UI of the website.

Also the **navbar is simple** with **no proper fonts added**

## Suggested changes : 
<ol>
<li>Appropriate padding of navbar</li>
<li>Styling of navbar</li>
<li>Ensure proper fonts for the website</li>
</ol>

**Comment by manu-hn** [comment]
Hey, @samyakmaitre , @laxmanp090404 , I would like to work on this.... Can you please assign me

**Comment by laxmanp090404** [comment]
@manu-hn  As per guidelines we could only work on some other person's issue only if they are **idle for a week** after assigning.
So i respectfully require the issue to be **assigned for me** as I was the **first to  raise the issue**

**Comment by manu-hn** [comment]
I got it @laxmanp090404 , please continue your work
