### ISSUE TITLE
Google SignIn using Firebase

### ISSUE THREAD

**Issue by samriddhitiwary** [samyakmaitre/eventmint#150]
I would like to implement Google authentication using Firebase. This feature would allow users to log in quickly and securely using their Google accounts, streamlining the authentication process and improving user experience. It can also enhance security by relying on Google’s authentication infrastructure, which is well-established and trusted.

![image](https://github.com/user-attachments/assets/fc564fbc-c239-4bdc-bcfc-0775cc6ac107)

**Comment by samriddhitiwary** [comment]
@samyakmaitre Could please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by samyakmaitre** [comment]
Ig this feature is already there. Kindly check yourself with the deployment and let me know.

![image](https://github.com/user-attachments/assets/02adaf94-efd8-46e9-8f19-ac56d7ce1cd0)

**Comment by samriddhitiwary** [comment]
@samyakmaitre Oh yes it's there I'm sorry

**Comment by samyakmaitre** [comment]
My bad, check signup page once, can you implement there?

**Comment by samyakmaitre** [comment]
its on login page

**Comment by samriddhitiwary** [comment]
@samyakmaitre Yes I can implement it

**Comment by samyakmaitre** [comment]
Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by samriddhitiwary** [comment]
@samyakmaitre Ok
