### ISSUE TITLE
Improving the Cards

### ISSUE THREAD

**Issue by samriddhitiwary** [samyakmaitre/eventmint#151]
I would like to improve the styling of the cards.

![image](https://github.com/user-attachments/assets/135b2162-1b1e-4f23-8e88-6ff4cc8f64d6)

**Comment by samriddhitiwary** [comment]
@samyakmaitre Could you please assign this issue to me under gssoc-ext and hacktoberfest

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
