### ISSUE TITLE
📃Feature Enhancement: Improve Navigation Bar

### ISSUE THREAD

**Issue by Rahul-AkaVector** [samyakmaitre/eventmint#155]
## Proposal for Navigation Bar Enhancement

I would like to propose an enhancement for the Eventmint website's navigation bar. I believe that we can make it more visually appealing and user-friendly.

### Proposed Changes:
- **Design Improvements**: Update the color scheme and typography for a modern look.
- **Usability Enhancements**: Implement dropdown menus for better organization of links.
- **Responsiveness**: Ensure the navigation bar works seamlessly across various devices (desktop, tablet, mobile).
- **Accessibility**: Incorporate ARIA roles and ensure keyboard navigation support.

### Request:
I would like to be assigned this task to develop and implement these changes. I’m excited to contribute and enhance the overall user experience of the website!

Labels: gssoc-ext, contributor, hacktoberfest
![Screenshot 2024-10-09 094358](https://github.com/user-attachments/assets/fa996ea1-477e-46d9-8ae6-9458b7c71f23)

@samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
