### ISSUE TITLE
Ticket Booking Card Feature Request 

### ISSUE THREAD

**Issue by ashishyadav512** [samyakmaitre/eventmint#158]
Please assign me the task of creating a ticket booking card that allows users to select and book movie tickets easily. When the card is clicked, it will redirect the user to a detailed booking page where they can provide necessary details such as movie time, cinema house name, seat selection, and other required information. This feature will streamline the booking process and improve user experience on the platform.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
