### ISSUE TITLE
Change name of project

### ISSUE THREAD

**Issue by ParulPrashar** [samyakmaitre/eventmint#16]
Change name from book my show to eventmint. 
please assign this issue to me @samyakmaitre kindly mention labels like gssoc-ext, hacktober fest

**Comment by AbhinabPalei** [comment]
hey @samyakmaitre please assign me this issue please mention labels like gssoc-ext

**Comment by ParulPrashar** [comment]
@samyakmaitre sir kindly add necessary labels hactoberfest, gssoc, level

**Comment by samyakmaitre** [comment]
@ParulPrashar Please go ahead and create PR. Create PR and I will add labels
