### ISSUE TITLE
Search Box not working

### ISSUE THREAD

**Issue by samriddhitiwary** [samyakmaitre/eventmint#160]
I would like to implement this search function where when user enter a movie he should be able to see it

**Comment by samriddhitiwary** [comment]
@samyakmaitre could you please assign this issue to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels.

Best regards,
Samyak

**Comment by samriddhitiwary** [comment]
@samyakmaitre I have raised a PR for this could you please review it

**Comment by samriddhitiwary** [comment]
@samyakmaitre The link of the PR is given below
https://github.com/samyakmaitre/eventmint/pull/161
