### ISSUE TITLE
[enhancement]: Develop Movie Details Page - Display Movie Information on Card Click

### ISSUE THREAD

**Issue by SwanandD121** [samyakmaitre/eventmint#162]
## Description
Currently, when a user clicks on a movie card, no movie details are displayed. We need to develop a **Movie Details Page** that will show the following information:
- Movie Title
- Description of the movie
- Trailer link (embed YouTube or video player)
- Photos carousel showcasing movie stills
- Cast photos
- "Book Tickets" button (navigates to ticket booking system)

## Steps to Reproduce
1. Open the application.
2. Click on any movie card in the movie listing.
3. Observe that no details are shown after clicking.

## Expected Behavior
Clicking on a movie card should take the user to a Movie Details Page that displays:
- Movie Title
- Movie Description
- Trailer link
- A photos carousel
- Cast photos
- A "Book Tickets" button

## Screenshots/Logs
N/A

## Environment
- **Operating System:** [e.g. Windows 11, macOS Ventura]
- **Node.js version:** [e.g. 18.x]
- **Browser/version:** [e.g. Chrome 117, Firefox 105]

## Additional Context
The Movie Details Page should be responsive across devices. Make sure the images and videos load efficiently, and the "Book Tickets" button should be visible and functional.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
