### ISSUE TITLE
The footer has the name bookmyshow rather than eventmint.

### ISSUE THREAD

**Issue by gaurkrutika** [samyakmaitre/eventmint#163]
![Screenshot (81)](https://github.com/user-attachments/assets/595bb3a5-930a-487a-aab4-ccd54d7903f1)
Assign this issue to me, @samyakmaitre. Please add the labels, such as gssoc extd hactoberfest level 2. Thankyou

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by gaurkrutika** [comment]
Sure, Thankyou
