### ISSUE TITLE
Update in Logo in Title

### ISSUE THREAD

**Issue by Sameeratweb** [samyakmaitre/eventmint#166]
![Screenshot 2024-10-09 131307](https://github.com/user-attachments/assets/3764ae5b-f693-439d-9d9a-c855bee4beed)
I want to update the logo with a more appropriate one.

I would like to work on it please allow me with issue with relevant tags under gssoc and hactoberfest.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. refer logo png from src folder. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
