### ISSUE TITLE
Bug when a new contributor clone your project there is some issues

### ISSUE THREAD

**Issue by Sawan-Kushwah** [samyakmaitre/eventmint#167]
![image](https://github.com/user-attachments/assets/f8f5358c-0395-40a9-9f4a-d274eb43af04)

returns something that is not valid JSON. 
If localStorage.getItem("token") is returning null (for instance, if no token is stored), then calling JSON.parse(null) will throw this error.

this bug occur to me when i clone your project to contribute but i catch by this error 
after finding a lot on internet i found a solution 

i can resolve this issue will you please assign me this

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
