### ISSUE TITLE
Fix in README 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [samyakmaitre/eventmint#168]
![image](https://github.com/user-attachments/assets/f0b5756a-542b-47f8-9fc5-f3406009876d)

as there written this is a educational website 

but content of website is of movie???

can i update it to movie event website in README from everywhere?

**Comment by samyakmaitre** [comment]
Upon review, the term 'educational institution' is present, but there is no mention of an 'educational website.'
share reference if found anywhere.

Regards,
Samyak Maitre
