### ISSUE TITLE
Poster of the movie and movie name is not matching 

### ISSUE THREAD

**Issue by rounakdey6** [samyakmaitre/eventmint#17]
![Screenshot 2024-10-01 234150](https://github.com/user-attachments/assets/b137e6d0-ea5c-4127-9793-e89fa24a3073)

**Comment by rounakdey6** [comment]
Please level this issue , and assign this to me

**Comment by rounakdey6** [comment]
Please level this issue , and assign this to me

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
