### ISSUE TITLE
Booking details page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [samyakmaitre/eventmint#170]
On clicking to book now button there should be a dedicated page where we see all the details of the movie

or we can also make form to fill his/her details and book it !!

can you assign me so that i can work?

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
