### ISSUE TITLE
Redesign of movie cards

### ISSUE THREAD

**Issue by Sawan-Kushwah** [samyakmaitre/eventmint#171]
![image](https://github.com/user-attachments/assets/3abaf017-2c75-4008-8519-c04d7c099e9c)

i can redesign this card in more professional look
as its main part of the eventMint so it should attract the user

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
