### ISSUE TITLE
Our team page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [samyakmaitre/eventmint#176]
here we showcase our team members and photos of our working and many more things

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

Counting issue #176 , #174 , #173 , #172 under #176 only

#176 Holds
- Our team page
- About us page is missing
- Contact us page
- Privacy policy page

**Comment by Sawan-Kushwah** [comment]
kind request can i make our team page and privacy policy page in one pr
and contact page in another PR

so that i am able to maximum points regarding GSSOC
