### ISSUE TITLE
Navbar changes

### ISSUE THREAD

**Issue by mrskjha** [samyakmaitre/eventmint#177]
Enhance the UI of Navbar and compliments the look and feel  of the home page.
![Screenshot 2024-10-09 145630](https://github.com/user-attachments/assets/7d04649a-4eef-4e8f-a5ef-b14a8b1694d6)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
