### ISSUE TITLE
when we click the  Book Ticket  button , it will show a pop up 

### ISSUE THREAD

**Issue by RockySheoran** [samyakmaitre/eventmint#178]
when we click the  Book Ticket  button , it will show a pop up that is your tickets is book.

**Comment by RockySheoran** [comment]
please assignee me .
labels - 2 level

**Comment by samyakmaitre** [comment]
The application should first navigate to the event description page, where the user can review event details. Once the user proceeds to the registration section, they should be able to fill in the required information. Upon successful completion of the registration and clicking the 'Book Ticket' button, a confirmation pop-up should be displayed to notify the user of the booking status.

Try working on this.

Regards,
Samyak
