### ISSUE TITLE
add footer section to the SIGNIN option/menu

### ISSUE THREAD

**Issue by Pranjalsinha110** [samyakmaitre/eventmint#180]
assign me to make the footer section of the signin option which will enhance your UI/UX and you will get more user engagement on your page.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by Pranjalsinha110** [comment]
assign me this task for GSSOC's
