### ISSUE TITLE
The whole website is not responsive.

### ISSUE THREAD

**Issue by roshanrich** [samyakmaitre/eventmint#181]
So,In the website if someone visit the first issue they will face is that none of the buttons work and it is not responsive at all,plus the photos of movies are still unmatched like for example:one movie named as hindustan 2 and the photo which showing is avatar ,so we need to change that
![Uploading Screenshot 2024-10-09 182908.png…]()

**Comment by roshanrich** [comment]
please assign me this @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
