### ISSUE TITLE
Overflow of Gray Navigation Bar (div)

### ISSUE THREAD

**Issue by 10xshivam** [samyakmaitre/eventmint#182]
![Screenshot 2024-10-09 182225](https://github.com/user-attachments/assets/91c920af-ea9e-4cc2-9069-cc31f41ab59f)
The gray navigation bar, containing links like "Movies," "Stream Events," "Plays," etc., is overflowing and extends beyond the intended layout. This could be affecting the overall user experience, as it disrupts the visual consistency of the page.

Additional Feature Suggestion: Theme Toggler
To enhance user experience, consider adding a theme toggler that allows users to switch between light and dark modes

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
