### ISSUE TITLE
Add User Reviews and Ratings

### ISSUE THREAD

**Issue by Anshikapal05** [samyakmaitre/eventmint#184]
Feature: Allow users to review and rate events they have attended. This adds credibility to the event and provides feedback to organizers.

@samyakmaitre could you please assign it to me?

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.

**Comment by samyakmaitre** [comment]
@Anshikapal05 
Hi,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
