### ISSUE TITLE
Switching of Dark Mode and Light Mode

### ISSUE THREAD

**Issue by Anshikapal05** [samyakmaitre/eventmint#185]
Allow users to switch between dark and light themes to enhance user experience and accessibility.
@samyakmaitre could you please assign to me?

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak
