### ISSUE TITLE
Fixing Footer

### ISSUE THREAD

**Issue by ezDecode** [samyakmaitre/eventmint#186]
**I have already Fixed the Footer Link Underline 
Added a arrow for scroll to the top
Fixed the Image Size in the Footer**

@samyakmaitre Consider it to assign me so that I can create a PR. I'm Adding some **images** below

![Screenshot 2024-10-09 184529](https://github.com/user-attachments/assets/0d4c9466-8809-45b3-89c9-f8c7ad46ed87)
![Screenshot 2024-10-09 184614](https://github.com/user-attachments/assets/4e0927a8-9a26-4206-8ff1-3ce4f2c18fdc)
![Screenshot 2024-10-09 184658](https://github.com/user-attachments/assets/16be8171-5b3e-456e-9dbb-fbbaf5e73e36)
![Screenshot 2024-10-09 185602](https://github.com/user-attachments/assets/bcd3d4d2-5f16-4aa8-986c-1788db2469b1)
![Screenshot 2024-10-09 185712](https://github.com/user-attachments/assets/2431013c-17d8-4c3f-abd9-ba309be96566)
![Screenshot 2024-10-09 190640](https://github.com/user-attachments/assets/7f0c312e-804c-4b1b-890c-7e881ff38c8e)
![Screenshot 2024-10-09 193545](https://github.com/user-attachments/assets/31be6c02-a299-4bc7-b180-53b6f1187bec)

**Comment by ezDecode** [comment]
@samyakmaitre assign this

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
