### ISSUE TITLE
UIUX enhancement 

### ISSUE THREAD

**Issue by Adrija05** [samyakmaitre/eventmint#188]
I would like to take on this issue and improve the visual layout to ensure the screen is aesthetically pleasing and user-friendly. My goal is to create a more cohesive design that will make the contact page visually appealing and aligned with the rest of the app, attracting more users to engage with it.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by Adrija05** [comment]
Hello ,
I was disappointed to see that this issue was closed, as I was still actively working on it and exploring the best ways to enhance the webpage. However, I have now completed my work and have created a pull request (#188) for the changes. Kindly review it at your convenience. Thank you

**Comment by Adrija05** [comment]
Atleast giving me level1 would have helped me a lot
