### ISSUE TITLE
Enhancing Carousel UI for better user experience

### ISSUE THREAD

**Issue by Anushkagupta2** [samyakmaitre/eventmint#19]
![image](https://github.com/user-attachments/assets/63ffb866-013a-43d3-91f0-3e1a10480dc9)
I wish to contribute in improving the UI of the carousel and making prominent side buttons which would make it much more visually appealing. Please assign this issue under the label gssoc-ext.

**Comment by samyakmaitre** [comment]
Please provide a preview, so that we can move forward.

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
