### ISSUE TITLE
Add Social Sharing features for event promotion

### ISSUE THREAD

**Issue by shrashti-19** [samyakmaitre/eventmint#190]
Implement social sharing buttons for each event to enhance visibility and engagement. Users should be able to share events easily on platforms like twitter(X), Instagram and WhatsApp. This feature can increase the attendance and provide valuable analytics for user engagement and event reach.

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.
