### ISSUE TITLE
Logo in footer is shrinked a lot

### ISSUE THREAD

**Issue by nishtha-902** [samyakmaitre/eventmint#194]
![image](https://github.com/user-attachments/assets/79d562d5-565f-454a-b878-6db46fd5d885)
please assign me this issue.

**Comment by SaanyaGarg5** [comment]
You can assign me this task under gsssoc and hacktoberfest level 3 label.

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
