### ISSUE TITLE
Footer layout and design needs enhancement for better alignment and aesthetics

### ISSUE THREAD

**Issue by Priyanshu282003** [samyakmaitre/eventmint#197]
Description:
The footer, as shown in the attached image, is not properly aligned and could benefit from improved styling for better user experience and visual appeal. Some elements seem misaligned, and the design feels cluttered on certain screen resolutions.

Issues Observed:
The alignment of text and icons is not uniform.
The "Stay Connected" section could be better positioned to improve balance with the rest of the footer.
The footer overall appears a bit disjointed, which may impact the user experience.
The "Scroll to Top" button placement looks odd and could be repositioned for better visibility and ease of use.
Suggestions for Enhancement:
Improve the spacing and alignment of text and icons for consistency across different sections.
Reposition the "Stay Connected" section to ensure it is better integrated with the footer design.
Optimize the layout for various screen sizes to maintain a clean and professional appearance.
Consider updating the "Scroll to Top" button design and position it in a way that complements the footer layout.
Environment:
Browser: Chrome , Firefox , etc.
Operating System: Windows 11.
Device: Desktop / Mobile
Screenshot:
![image](https://github.com/user-attachments/assets/725d80e9-7fca-4db2-a0cd-053c336db96c)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
