### ISSUE TITLE
Scroll reveal feature 

### ISSUE THREAD

**Issue by aditya07389** [samyakmaitre/eventmint#198]
Hey i want to add a scroll reveal feature to the website which will make it visually appealing ,it will look like this website :

https://www.nmit.ac.in/

kindly assign this to me with gssoc extd ,hacktoberfest and level 2

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by aditya07389** [comment]
Hey @samyakmaitre  , please add the labels and assign the issue to me , ill work on the issue and create the pr after that!!
