### ISSUE TITLE
navbar is not responsive for mobile,mac's and ipad

### ISSUE THREAD

**Issue by adityalaxkar123** [samyakmaitre/eventmint#201]

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by adityalaxkar123** [comment]
First gssoc ext label is mandatory for acceptance of issue
