### ISSUE TITLE
Footer drop downs need improvement

### ISSUE THREAD

**Issue by kushal7201** [samyakmaitre/eventmint#202]
### Description
Footer dropdowns affect the other components i.e the items in the dropdown shifts the entire design down which in turn affects user experience.

### Solution
- I'll make the dropdown items floating such that it does not affect the other components

https://github.com/user-attachments/assets/b2d9f0eb-6e98-4b31-8f91-696f1d2e1a6d

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
