### ISSUE TITLE
book ticket interface

### ISSUE THREAD

**Issue by Kushagrakatara89** [samyakmaitre/eventmint#203]
when click on book ticket an user interface should open for user to select @samyakmaitre 
assign me thius issue

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
