### ISSUE TITLE
[FEAT] : Add Sports Activities Page to EventMint Web Application

### ISSUE THREAD

**Issue by IkkiOcean** [samyakmaitre/eventmint#209]
## Description:

We need to introduce a dedicated Sports Activities Page to the EventMint web application. This page will serve as the go-to space for users to browse various sports events, featuring key details such as event titles, descriptions, venues, and dates. It should also highlight “Featured Sports Events” and provide an “Upcoming Sports” section for easy user access.

## Tasks:

	•	Design the UI for the Sports Activities Page.
	•	Include filtering and sorting features (by sport type, location, and date).
	•	Ensure full responsiveness for both mobile and desktop platforms.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by IkkiOcean** [comment]
@samyakmaitre sir, why did you closed the issue. should I create only one issue for both of the pages?
