### ISSUE TITLE
Add hover effect on "Book Ticket" button

### ISSUE THREAD

**Issue by shivamy009** [samyakmaitre/eventmint#21]
Add hover effect on button so than it become so attractive

**Comment by Mohith1490** [comment]
hey @shivamy009  can i work on this issue 
for gssoc

**Comment by komalnalage** [comment]
I’d love to work on enhancing the "Book Ticket" button by adding a hover effect. 
Could you assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute and believe this improvement will make a noticeable difference.

**Comment by ayushiu** [comment]
please assign this issue to me @shivamy009 under GSSOC-EXTENDED

**Comment by samyakmaitre** [comment]
@shivamy009  Please go ahead

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
