### ISSUE TITLE
 Logo Appearance in Dark Mode

### ISSUE THREAD

**Issue by PYIArun** [samyakmaitre/eventmint#210]
### Issue: Logo Appearance in Dark Mode

**Description:**
When using the light theme, the logo visually fits well with the background. However, in dark mode, the light background of the logo appears disconnected, creating a rectangular effect that doesn't blend well.

**Screenshots:**

- **Light Mode:**
  ![Light Mode](https://github.com/user-attachments/assets/4038cd64-74ca-4e04-8a8a-f82c30cd2516)

- **Dark Mode:**
  ![Dark Mode](https://github.com/user-attachments/assets/d3adf5b8-625a-4b32-9570-e2f6ab348e04)

**Suggestion:**
To improve the appearance in dark mode, we could modify the logo to look more integrated, similar to this example:

![Proposed Logo Design](https://github.com/user-attachments/assets/e2099abe-fe5f-4b00-b42e-401aba9f200e)

(Note: This is just a representation; the final quality should consider the original image.)

**Request for Assignment:**
I can work on this issue. Kindly assign it to me under `gssoc-ext` and `hacktoberfest-accepted` with a level (level 1/2/3).

Thank you!

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

Try using logo from src folder
