### ISSUE TITLE
Feature-Addition of Movie Recommendation System 

### ISSUE THREAD

**Issue by UTkARsh-RaJ01** [samyakmaitre/eventmint#211]
Adding a movie recommendation system to the event registration platform can greatly enhance user engagement by providing a more personalized experience. Since the platform is inspired by BookMyShow, offering movie recommendations would allow students and users to discover relevant entertainment options .

Assign this issue to me under GSSOC and Hacktober

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
