### ISSUE TITLE
Add "Forgot Password" Option to Login Page

### ISSUE THREAD

**Issue by saras-69** [samyakmaitre/eventmint#213]
Description: Add a "Forgot Password" link on the login page to allow users to reset their password. The link should direct users to a password recovery page, where they can enter their email and receive a reset link. Ensure proper validation and error handling.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by saras-69** [comment]
Could you please assigned me first
