### ISSUE TITLE
"Book tickets" button should be working.

### ISSUE THREAD

**Issue by mrunal1309** [samyakmaitre/eventmint#214]
The book tickets button on different cards is not letting book the tickets.@samyakmaitre can you please assign me this issue?

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
