### ISSUE TITLE
updated script for app.css 

### ISSUE THREAD

**Issue by akhulisumit** [samyakmaitre/eventmint#216]
updated script for app.css Lack of Visual Feedback on Interactive Elements:

The navigation links and buttons lacked modern hover effects like shadows or transitions, which are commonly used for better visual feedback. This can make the UI feel less responsive and interactive.
Flat Design:

The movie cards had very basic styling with a simple border and shadow, but the hover effect was not very noticeable. Modern UIs often use subtle animations, like scaling or shadow changes, to make interactions feel smoother.
Spacing and Alignment:

The spacing between elements (e.g., navigation items, movie cards) was somewhat tight, which could affect readability and visual hierarchy. Modern design usually emphasizes more space between elements for better clarity.
Typography:

The previous font was basic (Arial), which lacked the modern feel that a clean, professional font like Segoe UI or Roboto provides. Typography plays a huge role in enhancing readability and user engagement.
Button Design:

The buttons were functional but lacked a more refined, polished design. They didn’t have smooth color transitions or shadows, which are key to modern web design trends.
Lack of Smooth Transitions:

While there were some hover effects (like changing background colors), the transitions w

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
