### ISSUE TITLE
Dropdown items must have color according to theme

### ISSUE THREAD

**Issue by nishtha-902** [samyakmaitre/eventmint#217]
![image](https://github.com/user-attachments/assets/adf44762-147d-4d5f-8890-8c92485a888a)
please assign me this issue

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
