### ISSUE TITLE
Add Responsive Movie Component Using Tailwind CSS

### ISSUE THREAD

**Issue by mrskjha** [samyakmaitre/eventmint#218]
This PR updates the Movie component by replacing custom CSS with Tailwind CSS for a fully responsive design. The changes ensure that the layout adapts seamlessly across different screen sizes, providing a better user experience on both small and large devices.
![Uploading Screenshot 2024-10-11 033529.png…]()

**Comment by mrskjha** [comment]
assign me for this issues

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
