### ISSUE TITLE
Using a Movie api get lastest Movies 

### ISSUE THREAD

**Issue by jjf2009** [samyakmaitre/eventmint#219]
I would like to add a api system to get movies

**Comment by jjf2009** [comment]
Kindly assign me this issue under gssoc-ext hactobter level-3

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
