### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by TanviGandhotra** [samyakmaitre/eventmint#221]
we can add about section that properly describe this .I think we can make a single new page for this.

![image](https://github.com/user-attachments/assets/c9e7f689-7359-4cfe-b0c9-69bdd4446768)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by TanviGandhotra** [comment]
thnku @samyakmaitre . I will began my work today.
