### ISSUE TITLE
Feature: Sports Activites can be added

### ISSUE THREAD

**Issue by TanviGandhotra** [samyakmaitre/eventmint#222]
we can add sport activities section as clicking on its button doesnt work properly.

![image](https://github.com/user-attachments/assets/e0ed414c-e786-4033-9029-2c9088362de5)
I will make new page.Also contributed inGSSOC 24 so i feel i am capable of doing this

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
