### ISSUE TITLE
Feature: Book ticket section can be added

### ISSUE THREAD

**Issue by TanviGandhotra** [samyakmaitre/eventmint#223]
we can add book ticket section.Plzz assign me this issue so i can contribute to this wonderfull project.
![image](https://github.com/user-attachments/assets/d7fb0574-63ac-4d9b-8e20-a8258f00438f)
the above is just an example i will make it more enhancing.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by TanviGandhotra** [comment]
so should i started working . Plss Assign me this @samyakmaitre .
