### ISSUE TITLE
Feature: FAQ'S section to be added

### ISSUE THREAD

**Issue by TanviGandhotra** [samyakmaitre/eventmint#224]
there is no FAQ section.and this is most imp section in a website.plzz assign me this issue so i can contribute.

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
