### ISSUE TITLE
Strength of the password

### ISSUE THREAD

**Issue by Arveti-likhitha** [samyakmaitre/eventmint#226]
While entering the password, changes could be made to show the strength of the password and not allow the user to sign in until the password is strong or medium.

![Screenshot 2024-10-11 110752](https://github.com/user-attachments/assets/819f871a-3e94-4ce3-8d41-b937bb5d0815)

@samyakmaitre please assign this to me and add the labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
