### ISSUE TITLE
[feature]: Add Back to Top Functionality

### ISSUE THREAD

**Issue by faiz66388** [samyakmaitre/eventmint#227]
Description:
The event registration platform lacks a "Back to Top" button functionality, which would enhance user experience by allowing users to quickly navigate to the top of the page, especially on longer event listing pages.

Steps to Reproduce:
Navigate to any event listing page on the platform.
Scroll down the page to view various events.
Notice that there is no button or link to quickly return to the top of the page.
Expected Behavior:
Users should be able to click a "Back to Top" button, which smoothly scrolls the page back to the top, improving navigation and user experience.

Actual Behavior:
Currently, users must scroll manually back to the top of the page, which can be inconvenient on longer pages.

**Comment by AsifQamar** [comment]
@samyakmaitre please assign me this issue

**Comment by samyakmaitre** [comment]
@faiz66388 

Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
