### ISSUE TITLE
Add previous and next buttons at home page 

### ISSUE THREAD

**Issue by swathivemula7** [samyakmaitre/eventmint#228]
I would like to add navigations buttons to the slider at the home page of the website.

![Capturejdmvj](https://github.com/user-attachments/assets/4bef2102-92fd-4551-93ae-8c0a14798ba7)
@samyakmaitre Kindly assign me this issue under the labels gssoc;24 and hacktoberfest

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
