### ISSUE TITLE
[fix]:No privacy policy page for the link in the footer 

### ISSUE THREAD

**Issue by Vaishh18** [samyakmaitre/eventmint#230]
Description:
The "Privacy Policy" link in the website footer currently leads to a non-existent or incorrect page. This issue affects the user experience and legal compliance, as users are unable to view our privacy policy.

Proposed Fix:
Create a new "Privacy Policy" page that details how user data is collected, stored, and managed.
Link the footer's "Privacy Policy" text to the newly created page.
Ensure the link is functional and directs to the correct URL for the privacy policy.
Add a section to the page where users can contact us regarding privacy concerns.
![Screenshot 2024-10-11 204633](https://github.com/user-attachments/assets/151d63cf-5e75-4117-bfde-d47d44042444)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
