### ISSUE TITLE
Website is not responsive on mobile screens(hactoberfest)

### ISSUE THREAD

**Issue by MisbahAnsar** [samyakmaitre/eventmint#235]
- The website is not properly responsive on mobile devices. Content appears misaligned, certain elements are either overlapping or cut off, and some features (e.g., navigation menus, buttons, forms) are difficult to use.
- The issue might be caused by missing media queries, incorrect use of flex/grid layouts, or lack of mobile-first design principles.
- I am interested in working on this issue and would like to contribute by making the necessary changes to ensure the website is responsive for mobile screens
- here's a video where i've captured the issue

https://github.com/user-attachments/assets/fc8d77f4-5109-4e2f-873f-555f121eea15

**Comment by MisbahAnsar** [comment]
@samyakmaitre assign this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
