### ISSUE TITLE
ADD links to the social icons

### ISSUE THREAD

**Issue by akanksha1055** [samyakmaitre/eventmint#237]
![image](https://github.com/user-attachments/assets/b6fd3f51-8ca1-486d-8849-84ebc866482a)
Currently as the social icons redirect to the home page only . I would like to add the correct social linksto the icons improving the interface .

please assign me this under GSSSOC and HACKTOBER 

thankyouuu

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by akanksha1055** [comment]
can you provide the social links for the project or your personal socials that u want to link for the same . Thankyou for assigning me this issue !!
