### ISSUE TITLE
Add Sign In And Login Functionality

### ISSUE THREAD

**Issue by Mdraza78** [samyakmaitre/eventmint#24]
Currently, the application lacks a proper Sign In and Login system, preventing users from accessing personalized features.

Proposed Solution:
Implement both Sign In and Login functionality:

Sign In: Allow new users to create an account with their details (e.g., name, email, password).
Login: Enable existing users to log in using their registered credentials.

**Comment by rounakdey6** [comment]
please level this issue and assign this to me

**Comment by vararaghu002** [comment]
Interested to work on this project, pls assign to me.

**Comment by harshbhar0629** [comment]
@samyakmaitre  Can i work on this issue??

**Comment by saimohan11** [comment]
I am interested to work on this issue assign this to me

**Comment by Kameshnic** [comment]
interseted to work on thiis proejct kindly assign the issues to me i will fix
