### ISSUE TITLE
Enhancement of Login and Signup page

### ISSUE THREAD

**Issue by usha-here** [samyakmaitre/eventmint#244]
Good morning @samyakmaitre sir, 
I saw in your website the login and sign up page do not have a very good UI design . The image is not coming complete in background and is even blur in login page.
![image](https://github.com/user-attachments/assets/06d2ed87-96f4-49f9-8a97-c740cbc87eeb)
![Screenshot 2024-10-12 093809](https://github.com/user-attachments/assets/c4018b42-8e65-498b-b498-4b6f565deb7c)

I would like to make a new issue and enhance the design of both login and sign up page, So if you could please assign me this , 
I would be  really grateful 
Thankyou.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
