### ISSUE TITLE
Add Back to top symbol

### ISSUE THREAD

**Issue by pavitraag** [samyakmaitre/eventmint#249]
Using back to top symbol we can move up easily. Please assign this to me under gssoc extd and hacktoberfest.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak


try adding it above chatbot at right bottom corner
