### ISSUE TITLE
responsiveness to page 

### ISSUE THREAD

**Issue by Mdraza78** [samyakmaitre/eventmint#25]
The card headers on the frontend are not fully responsive, leading to layout issues on different screen sizes, especially smaller devices.

Proposed Solution:
Ensure that the card headers adapt to various screen sizes by implementing responsive design techniques (e.g., using flexbox, media queries, or Bootstrap classes). This will ensure a consistent and user-friendly experience across all devices.

**Comment by AbhinabPalei** [comment]
can you please assign me this issue

**Comment by Saketh1714** [comment]
can you assign this issue to me

**Comment by samyakmaitre** [comment]
issue resolved already by another PR
