### ISSUE TITLE
Enhancing Movie Database on Event Mint for Improved User Engagement

### ISSUE THREAD

**Issue by tejasam571** [samyakmaitre/eventmint#250]
**Title:** *Enhancing Movie Database on Event Mint for Improved User Engagement*

**Description:**  
As a contributor to the GSSoC Extended and Hacktoberfest initiatives, I propose to enrich the Event Mint webpage by adding a wider selection of movies. Expanding our movie database will provide users with more comprehensive reviews and detailed information, fostering a deeper connection with the content. By integrating diverse genres and titles, we can cater to a broader audience, ensuring that users find films that resonate with their interests. This enhancement will not only improve user engagement but also encourage discussions and interactions within our community, ultimately elevating the overall experience on the Event Mint platform.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
