### ISSUE TITLE
[Feature] Adding Animation when Theam switch

### ISSUE THREAD

**Issue by Nagesh-tri** [samyakmaitre/eventmint#251]
when one click on Theam button, the color changes so quickly which affects the user experience.
To overcome this one can add some basic animation stuff while switching mode.

<h2> Solution :</h2>
adding animation to background color.

would you assign this to me as gssoc ext contributor with proper lables

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
