### ISSUE TITLE
To fetch the latest movies via an api and recode the whole movie listings

### ISSUE THREAD

**Issue by ayush-848** [samyakmaitre/eventmint#254]
So this part will be dynamic and the latest releases will gets updated
(Optionally I can give user option to choose language)

**Comment by ayush-848** [comment]
@samyakmaitre Please assign this issue to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by ayush-848** [comment]
@samyakmaitre why have you closed this issue??
