### ISSUE TITLE
Update the plays section with an API

### ISSUE THREAD

**Issue by sindhuja184** [samyakmaitre/eventmint#255]
![image](https://github.com/user-attachments/assets/d782652e-eaf9-4fbd-a8a0-b82e3412bdea)
I can make use of api's like EventBrite API V3 to fetch the latest information about plays so that the user can get a real time experience.

Please assign this issue to me I am eager to work on it.

Thanks @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
