### ISSUE TITLE
Adding Relative Image 

### ISSUE THREAD

**Issue by Sameeratweb** [samyakmaitre/eventmint#256]
![Screenshot 2024-10-12 224205](https://github.com/user-attachments/assets/e4450772-f443-45d1-a595-04d4aee1b9ef)
Adding an Relative image logo such that it matches background , some changes are to  be made then please allow me this issue.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

Kindly refer src folder for logos
