### ISSUE TITLE
Adding contact us page where users can reach out for feedback or queries.

### ISSUE THREAD

**Issue by riddhij0804** [samyakmaitre/eventmint#258]
Currently, the contact us link in the help and support section in the footer is not leading anywhere.
I would love to contribute by creating a contact us page.
The form would include the following -
**Form Fields :**

1. Name
2. Email
3. Subject
4. Message

**Kindly assign this issue to me.**

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
