### ISSUE TITLE
Add a toggle button for small pages

### ISSUE THREAD

**Issue by sayanp607** [samyakmaitre/eventmint#259]
![Screenshot 2024-10-13 003156](https://github.com/user-attachments/assets/78fd4731-904a-499b-a0ea-c4adc8f53d3b)
The options in the header looks messy in small screens. Please assign this task to me, I will create a toggle button that appears for small pages and contains the options. I am quite experienced as I developed this feature manytimes.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
