### ISSUE TITLE
Need Improvement in header:-searchbar,logo,sign in button

### ISSUE THREAD

**Issue by Trumilnasit** [samyakmaitre/eventmint#26]
@samyakmaitre -Can you assign me this project i would like to contribute into it and also add some labels to this issues .

**Comment by samyakmaitre** [comment]
Please continue with search bar, logo. sign in button issue is already resolved. You can choose Logo from src folder.
Kindly replace bookmyshow with the logo provided.

**Comment by samyakmaitre** [comment]
No response received, issue resolved by another PR.
