### ISSUE TITLE
Add login button at home page 

### ISSUE THREAD

**Issue by lakshmirajvagu** [samyakmaitre/eventmint#261]
![Screenshot_2024-10-13-07-45-31-24_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/7087d2e5-3d39-46b1-960d-1aa13435c194)
Will add a login page instead of sign in please assign to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Sign in and log in are both in the same button already.
