### ISSUE TITLE
Fix logo in Header section 

### ISSUE THREAD

**Issue by Sameeratweb** [samyakmaitre/eventmint#263]
![Screenshot 2024-10-13 083450](https://github.com/user-attachments/assets/15f0b137-44ae-4433-854c-7e18b95ddc96)
While in Dark mode, the logo looks appropriate. I can work to fix the logo with the background color while using dark mode. Please assign me this issue.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
