### ISSUE TITLE
Adding input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [samyakmaitre/eventmint#264]
Hello
I would like to add proper input form validations to the login and signup pages
pls assign this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
