### ISSUE TITLE
Adding information to offers page

### ISSUE THREAD

**Issue by Gauravtb2253** [samyakmaitre/eventmint#265]
Hello I would like to add content to the offers page so that users can get to know more about it
Pls assign this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
