### ISSUE TITLE
Adding content to listing your show page

### ISSUE THREAD

**Issue by Gauravtb2253** [samyakmaitre/eventmint#266]
Hello I would like to add proper content to the listing your show page so that production companies can add their shows to the website
Pls assign this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
