### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by MisbahAnsar** [samyakmaitre/eventmint#267]
i've gone through the codebase, and in user schema there is no zod validation, zod validation is used for 
- Zod allows you to define schemas for objects, arrays, and other data types.
- Zod provides detailed error messages when validation fails.
- Zod automatically infers TypeScript types from schemas, ensuring type safety without extra effort.

eg: as of now ur website taked input for password anything, and not any limit like a user can even put 3chars in it, but thats not good, the minimum password input should be 8characters in which it should contain atleast one number and 1 special character

note: i am ready to work on this issue(hactoberfest+gssoc-ext)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
