### ISSUE TITLE
Missing Ticket Booking Page with No Back Navigation & Refresh Functionality

### ISSUE THREAD

**Issue by 007-AnuRV** [samyakmaitre/eventmint#268]
I notice the following issue : 
**No ticket Booking Page :-** There is no dedicated page for booking tickets, which is essential for users.
**No Back Button :-** The booking page lacks a back button , making it difficult to return to the home page or previous sections.
**Refresh Issue :-** Clicking the refresh icon on the booking page does

**Comment by 007-AnuRV** [comment]
Please assign me this task

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

sync your fork, check areas you will be working on, then start.

Best regards,
Samyak

**Comment by 007-AnuRV** [comment]
Hi Samyak,
Thank you for the guidance! I’ll go ahead and sync my fork, check the relevant areas, and start working on the issue. I’ll keep you updated and will create a pull request once the changes are ready. I’ve also connected with you on GitHub. Looking forward to collaborating!

Best regards,
Anukriti
