### ISSUE TITLE
Adding contributors photos in readme

### ISSUE THREAD

**Issue by ArchanRD** [samyakmaitre/eventmint#271]
We can add photos of all the contributors in the readme section as part of praising them for their awesome contributions. 
![image](https://github.com/user-attachments/assets/288ed7b9-5566-4dd7-b04e-90db7d85ee7c)

Similar to the above. Please assign this issue to me.

**Comment by 2MJ-DEV** [comment]
I request that this task be assigned to me. Thank you!!

**Comment by samyakmaitre** [comment]
![image](https://github.com/user-attachments/assets/074801d4-6394-4aea-a90a-f4ea5233f42d)

its already there, and therefore I do not find any necessity of it.

Thank you.

**Comment by 2MJ-DEV** [comment]
Yet there is not!!
