### ISSUE TITLE
I create issue , you work! | Check inside

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#273]
I'll be posting my requirements for Event Mint here. Issues will be assigned on a first-come, first-served basis, along with the appropriate labels. Keep an eye in here for updates to earn more points! 😉

Procedure:

1. I will comment down the issue.
2. The first person to ask for it will be assigned the issue.
3. Once assigned, you can start working and submit a PR.
4. We'll collaborate on any necessary changes to the PR.
5. After the changes are approved, the PR will get labelled, merged, and you're all set!

Although you're welcome to create your own separate issues other than these. Before working on any issue, please make sure to sync your fork. And don't forget to connect with me on GitHub!

**Comment by samyakmaitre** [comment]
![image](https://github.com/user-attachments/assets/50b11e1c-0fbf-49ce-8b69-7c02e864d407)

Issue with hover underline for nav list, anyone want to work on this?

**Comment by jeevika17** [comment]
> CI1
> 
> ![image](https://private-user-images.githubusercontent.com/130790017/376029124-50b11e1c-0fbf-49ce-8b69-7c02e864d407.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkxMzMsIm5iZiI6MTcyODgxODgzMywicGF0aCI6Ii8xMzA3OTAwMTcvMzc2MDI5MTI0LTUwYjExZTFjLTBmYmYtNDljZS04YjY5LTdjMDJlODY0ZDQwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGM5MmFhZGNmMjFmZWMwNGFhMWVlMjFiMzllN2M3NDU1MjI4NTFiYmFjMWE0OGE3MjRhNTUyYzdiOTIyMTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JwgGQ_i65zDHTHiV6nboFsvzVjQcILpaZn4-gWop8to)
> 
> Issue with hover underline for nav list, anyone want to work on this?

i want to do it assign me

**Comment by samyakmaitre** [comment]
@jeevika17 please go ahead, work on it and mention #EM1

**Comment by samyakmaitre** [comment]
EM2

![image](https://github.com/user-attachments/assets/82f833b9-7207-406a-a343-24bf60277c16)
I want footer alignment like this.

**Comment by samyakmaitre** [comment]
EM 3
![image](https://github.com/user-attachments/assets/ff8ddf08-0451-41ce-ba65-55735b59e9e7)


I want black header and grey navbar in dark mode.

**Comment by samyakmaitre** [comment]
EM4
![image](https://github.com/user-attachments/assets/4b7f4a51-27f9-4518-bcdc-72583b0fad74)

Similar CSS for dropdown as of signin button.

**Comment by samyakmaitre** [comment]
EM5 
A smooth transition from light to dark mode and vice versa.

**Comment by samyakmaitre** [comment]
![image](https://github.com/user-attachments/assets/80071a1e-80e8-4a17-8980-e808901efa73)

A similar side panel as on bookmyshow. Check [bookmyshow.com](https://in.bookmyshow.com/)

**Comment by samyakmaitre** [comment]
EM7

From this:
![image](https://github.com/user-attachments/assets/2818d003-9d95-45b8-a335-d8fcfd1a7333)

To this:
![image](https://github.com/user-attachments/assets/7be1bdc3-f57b-4e79-a9a0-df97dfa55474)

**Comment by samyakmaitre** [comment]
> please go ahead, work on it and mention #EM1 in PR.
> 
> Regards, Samyak

please go ahead, work on it and mention #EM3 in PR.

Regards,
Samyak

**Comment by samyakmaitre** [comment]
EM8

From this: 
![image](https://github.com/user-attachments/assets/5a739f6d-7414-4e9f-8cd1-78563cf52c19)

To this:
![image](https://github.com/user-attachments/assets/a26f8739-79df-471d-8de2-431ddf7dbf62)

**Comment by TanviGandhotra** [comment]
will work on #EM4

**Comment by samyakmaitre** [comment]
> please go ahead, work on it and mention #EM3 in PR.
> 
> Regards, Samyak

please go ahead, work on it and mention #EM4 in PR.

Regards,
Samyak

**Comment by Ibrangrd** [comment]
i will work on issue #EM2 . so , @samyakmaitre  assign to me .

**Comment by Dev-Rishav** [comment]
I would like to work on #EM6 issue. Please assign it to me! @samyakmaitre

**Comment by samyakmaitre** [comment]
> please go ahead, work on it and mention #EM4 in PR.
> 
> Regards, Samyak

please go ahead, work on it and mention #EM2 in PR.

Regards,
Samyak

**Comment by samyakmaitre** [comment]
> I would like to work on #EM6 issue. Please assign it to me! @samyakmaitre

please go ahead, work on it and mention #EM6 in PR.

Regards,
Samyak

**Comment by Phanisirisha-46** [comment]
I would like to work on #EM7 issue. Please assign it to me! @samyakmaitre

**Comment by Gauravtb2253** [comment]
I want to work on #EM8 pls assign me

**Comment by samyakmaitre** [comment]
@Phanisirisha-46 
please go ahead, work on it and mention #EM7 in PR.

Regards,
Samyak

**Comment by samyakmaitre** [comment]
@Gauravtb2253 please go ahead, work on it and mention #EM8 in PR.

Regards,
Samyak

**Comment by samyakmaitre** [comment]
#EM9

![image](https://github.com/user-attachments/assets/45082927-679f-4ebf-8b9e-db77269bc1d0)


reduce this space

**Comment by Gauravtb2253** [comment]
I would like to work on EM9 
pls assign me

**Comment by LalithKumar77** [comment]
Hello @samyakmaitre 
I would like to work on EM7
pls assign me

**Comment by Gauravtb2253** [comment]
> @Gauravtb2253 please go ahead, work on it and mention #EM8 in PR.
> 
> Regards, Samyak

in EM8 do you need to display the little part of previous and next image also

**Comment by samyakmaitre** [comment]
@Gauravtb2253 yes

**Comment by samyakmaitre** [comment]
@LalithKumar77 EM7 is already assigned

**Comment by samyakmaitre** [comment]
#EM9  to  @Gauravtb2253

**Comment by samyakmaitre** [comment]
#EM10

From this:
![image](https://github.com/user-attachments/assets/cfce32e6-b8a7-491e-b71c-0d06153a9853)

To this:
![image](https://github.com/user-attachments/assets/e7ad09ba-0e52-4d0b-9bd7-13722785ee79)

**Comment by samyakmaitre** [comment]
@Gauravtb2253  please proceed with #EM10

**Comment by LalithKumar77** [comment]
@samyakmaitre is there any other issue ?. please inform me  and i will look into that issue

**Comment by samyakmaitre** [comment]
#EM11

From this:
![image](https://github.com/user-attachments/assets/a4f4ea07-32db-493e-9e85-867c6316a3e3)


To this: 
![image](https://github.com/user-attachments/assets/b3957a7a-f2c0-4097-9df5-5f15ace10b3f)

**Comment by samyakmaitre** [comment]
#EM12

![image](https://github.com/user-attachments/assets/099d34fc-09de-49cc-956a-1fa338df662a)

**Comment by Gauravtb2253** [comment]
assign EM11 and EM12 to me pls

**Comment by NazTM** [comment]
@samyakmaitre Can I add my own issue? I'd like to extend the dark mode to the login page as well.

**Comment by samyakmaitre** [comment]
@NazTM create your issue outside this, here I will be posting my requirements in project.

**Comment by Ankitha2130** [comment]
I would like to work on EM11

**Comment by ayushig05** [comment]
@samyakmaitre I want to contribute to the EM11. Can you please assign me that task?

**Comment by samyakmaitre** [comment]
@ayushig05  
please go ahead, work on it and mention #EM11 in PR.

Regards,
Samyak

**Comment by samyakmaitre** [comment]
@Ankitha2130 
work on #EM12

Regards,
Samyak

**Comment by Hemraj-7** [comment]
I want to make card responsive in the home page. Now these cards are not responsive in the small device

![Screenshot 2024-10-16 235713](https://github.com/user-attachments/assets/8e3b0410-cec2-43d0-8123-460a37116d6a)

**Comment by samyakmaitre** [comment]
@Hemraj-7 create your issue and PR outside this.

**Comment by Rup22esh** [comment]
> EM6
> 
> ![image](https://private-user-images.githubusercontent.com/130790017/376032460-80071a1e-80e8-4a17-8980-e808901efa73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDc1MzEsIm5iZiI6MTcyOTEwNzIzMSwicGF0aCI6Ii8xMzA3OTAwMTcvMzc2MDMyNDYwLTgwMDcxYTFlLTgwZTgtNGExNy04OTgwLWU4MDg5MDFlZmE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxOTMzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTJkNTg1ZmY2OWNhNWFmNGMyMGIwZTVlOGQ2OTM4ODBmNTA0ZGVjNzc5YTQ1NmRlZWYwOWYyMTAzOTg5ZjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u0CvmCOuZfmbEks42jTpzqCmWJrQ3vU9ncB8yfku4Us)
> 
> A similar side panel as on bookmyshow. Check [here](https://in.bookmyshow.com/)

I would like to work on EM6 issue. @samyakmaitre please assign me to work on this

**Comment by 30Abhi** [comment]
sir I am working on the issue that you have provided to me . Can we connect on discord because I want to clarify the the changes and implemetation I have done is up to the mark or not.
![image](https://github.com/user-attachments/assets/8f33c710-919f-4af6-931d-e84b6561de88)

**Comment by samyakmaitre** [comment]
@Rup22esh #EM6 is already assigned

**Comment by samyakmaitre** [comment]
Please work on it, those who got their task, further requirements from my side will be posted under Issues section directly.
