### ISSUE TITLE
BUG: No input validation in Auth-Forms

### ISSUE THREAD

**Issue by harshbhar0629** [samyakmaitre/eventmint#277]
There is no input validation in Auth form, login and signup forms and also not implemented regex check validation in forms.

Regex provide safe and secure input:

Example Regex Patterns:
Email Validation: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
Phone Number Validation: ^\+?(\d{1,3})?[-. ]?(\d{10})$
Password Validation (at least one uppercase, one lowercase, one number, one special character, and 8-20 characters): ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,20}$

@samyakmaitre Please assign to me this issue under the label of **hacktoberfest-accepted, gssoc-ext, level-2**.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by harshbhar0629** [comment]
Ok but please do not close issue otherwise how can i enter the issue number:)
