### ISSUE TITLE
Offers Page not working 

### ISSUE THREAD

**Issue by 1ShahidBashir** [samyakmaitre/eventmint#282]
@samyakmaitre I was going through the website and I noticed the offers page is not working
![image](https://github.com/user-attachments/assets/9568c776-e849-43c5-83cd-28c44d7acb22)

**Comment by 1ShahidBashir** [comment]
@samyakmaitre assign this issue to me, tell me what you need and we can do whatever is possible by our side

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
