### ISSUE TITLE
Add more movie cards & Sign in /out functional 

### ISSUE THREAD

**Issue by Jainpaswan** [samyakmaitre/eventmint#283]
Add more Movies cards that are recently released.
There is problem in Sign up feature..(more detail needed)

**Comment by Jainpaswan** [comment]
Assign this to me ... I will fix this..please

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
