### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by Jainpaswan** [samyakmaitre/eventmint#284]
While turning to dark mode  it should make the logo dark to for better UI experience
![Screenshot 2024-10-13 234917](https://github.com/user-attachments/assets/ce45f692-7a7c-4b28-88dc-2442723aba7f)

**Comment by Jainpaswan** [comment]
Assign it to me i will fix it..please

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
