### ISSUE TITLE
Password Recovery Component 

### ISSUE THREAD

**Issue by saras-69** [samyakmaitre/eventmint#285]
Description:
Implement a Password Recovery feature within the login/signup workflow to enhance user experience and account management.

Tasks:

Create a modal for password recovery with smooth open/close transitions.
Add a recovery form where users can enter their email to receive recovery instructions.
Validate email format and show success or error messages.
Integrate with backend (if available) to simulate email recovery logic.
Ensure UI is consistent with the existing design and transitions are user-friendly.
Expected Outcome:
A functional Password Recovery component that allows users to recover their accounts with ease. This feature will improve user accessibility and satisfaction.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by saras-69** [comment]
I already created PR 
https://github.com/samyakmaitre/eventmint/pull/286#issuecomment-2409863621
