### ISSUE TITLE
UPDATION IN README FILE REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [samyakmaitre/eventmint#287]
Hello @samyakmaitre 

the current readme file lacks proper structure and does not contain the following :

-featured in section
-table of contents
-contributors 
-forkers and stargazers section
-back to top button

kindly assign me the issue under gssoc-extd and hacktoberfest labels so my work counts under these events
Thankyou .

**Comment by samyakmaitre** [comment]
No requirement at this point of time.

Thank you.
