### ISSUE TITLE
Addition of Webinar and Fest section for college students

### ISSUE THREAD

**Issue by Rupendra0** [samyakmaitre/eventmint#290]
We can add Fest , webinars and Hackathon sections in nav bar and also dedicate a separate 
Page for them for college students because student doesn't have info about Hackathon and fests.
I cab work on its front end .

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

Make these section some where under nav bar menu options.

**Comment by Rupendra0** [comment]
Okay i will ....
