### ISSUE TITLE
Remove Unnecessary Width 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [samyakmaitre/eventmint#293]
There is unnecessary width causing unwanted horizontal scrolling. Please remove the extra width to prevent the page from scrolling horizontally.

**Comment by gurramkarthiknetha** [comment]
i want to fix this issue please assign me

**Comment by AnushkaChouhan25** [comment]
Can you please assign this issue to me under gssoc-ext and hactoberfest-accepted, I want to contribute in it. Thank you!
![image](https://github.com/user-attachments/assets/4f4578b2-e3e4-4e2f-a3e9-82a610e5e25d)

**Comment by samyakmaitre** [comment]
@AnushkaChouhan25 
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by AnushkaChouhan25** [comment]
@samyakmaitre Okay I'll do, but why the issue is closed.
