### ISSUE TITLE
Implement header section and book ticket section and interaction of the home page images 

### ISSUE THREAD

**Issue by 30Abhi** [samyakmaitre/eventmint#296]
1.Header section [Movies] 
[Stream Events]
 [Plays]
 [Sports Activities] is missing implementation . 
2.Book Ticket section is missing 
3.There is no interactive implementation of home page images 

I want excited to work on this part of website . Kindly assign me this  . I am attaching images of issue below.

![image](https://github.com/user-attachments/assets/8b8c6ff9-cdb7-4961-abd0-f1f4881a92e4)
![image](https://github.com/user-attachments/assets/89a9626e-018d-4d04-8b73-b270e6280bae)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by samyakmaitre** [comment]
follow

**Comment by samyakmaitre** [comment]
Kindly look into webpage and your work proposed, then start working on it, do not work on feature that are already there. Also sync your fork.

**Comment by 30Abhi** [comment]
Sir I have made pull request please check it

**Comment by samyakmaitre** [comment]
wait

**Comment by samyakmaitre** [comment]
Sync your fork
