### ISSUE TITLE
UI Alignment and Navigation Enhancements

### ISSUE THREAD

**Issue by Kavish-Paraswar** [samyakmaitre/eventmint#299]
The current UI requires improvements in image and text alignment. The image should be centered for better visual appeal, and the text and information aligned properly to enhance clarity. 
![image](https://github.com/user-attachments/assets/31f342f7-feeb-41cd-9524-a427044f7c54)

 Specifically, the image and text related to Actor 1 need proper alignment. Additionally, there are no back buttons or links to the homepage on any webpages. Adding these will improve navigation and usability.
![image](https://github.com/user-attachments/assets/1bcc2908-e543-43b1-bbf1-02c33d0bac95)

I'd like to handle this task under GSOC '24 Extended and request it be assigned at Level 1 or 2. I have strong expertise in HTML, CSS, and JavaScript.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by Kavish-Paraswar** [comment]
why did u close this issue ? if the work is to be done.

**Comment by samyakmaitre** [comment]
Create PR directly I have no problem
