### ISSUE TITLE
 [UI/UX Overhaul & Feature Upgrade]: Modernize Footer, Buttons, Add Dynamic Sliders, Search Functionality, and Firebase Auth

### ISSUE THREAD

**Issue by Nkovaturient** [samyakmaitre/eventmint#3]
Hello @samyakmaitre ,  I propose to enhance the overall UI/UX of the web application to better reflect the app’s brand identity and  improve user experience. This will involve--

**Frontend: -**
-  updating the footer content &  styling,
- styling buttons to achieve a more modern and cohesive design
- Adding dynamicity by integrating image sliders and more movie cards.

**Backend:-**
- I will also try to integrate search functionality for better retrieval of data
- Firebase Auth Integration for users to signup/login on your web app.

Kindly assign me these proposed changes under GSOC extd-2024.
Looking forward to your response. :))

**Comment by samyakmaitre** [comment]
issue resolved
