### ISSUE TITLE
Add Login/Signup Component

### ISSUE THREAD

**Issue by saras-69** [samyakmaitre/eventmint#30]
Description:
I want to implement a login and signup component in the application using React.js. This component will allow users to register for new accounts and log in to their existing accounts.

Proposed Solution:

Design separate forms for login and signup, with input validation (e.g., email, password).
Implement state management to handle user inputs and authentication status (e.g., using React hooks or context).
Integrate authentication with a backend service (e.g., using JWT or OAuth).
Ensure error handling for failed login/signup attempts and display appropriate messages.
Add styling for the forms to ensure a user-friendly interface, responsive across devices.
Benefits:

Provides users with a secure way to log in and register.
Enhances user engagement by allowing personalized access to features.

**Comment by samyakmaitre** [comment]
Issue already raised and assigned at #38

**Comment by saras-69** [comment]
Hey @samyakmaitre, I just wanted to let you know that I already raised this issue for #30, and I noticed there’s no JWT implementation in #38. Could you please check and clarify both?
