### ISSUE TITLE
Want to add a cool loader 

### ISSUE THREAD

**Issue by PulkitShubham** [samyakmaitre/eventmint#302]
Kindly assign this task to me @samyakmaitre .....I would love to work on it

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by PulkitShubham** [comment]
Okayy @samyakmaitre

**Comment by PulkitShubham** [comment]
@samyakmaitre Kindly check my PR #308
