### ISSUE TITLE
View password feature on login and Sign Up page

### ISSUE THREAD

**Issue by Preethii-R** [samyakmaitre/eventmint#303]
### **_I noticed that the sign-up form currently lacks a "view password" option, which could lead to user errors. I would like to take on the task of implementing this feature to enhance user experience. Please let me know if I can proceed with this improvement._**

I am confident that resolving these issues will improve the page's usability and overall aesthetic. Please let me know if I can take on this task and contribute to improving the website.

**Comment by samyakmaitre** [comment]
This feature is already there.
Thank you
