### ISSUE TITLE
Issue: Extending dark mode to login page

### ISSUE THREAD

**Issue by NazTM** [samyakmaitre/eventmint#309]
I noticed the dark mode doesn't extend to the login/signup page
Please assign gssoc-ext and hacktoberfest

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
