### ISSUE TITLE
By Admin | Issue under "More Details"

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#310]
From this:
![image](https://github.com/user-attachments/assets/a5187d37-b14b-45a5-9f80-979a2708f779)

To this: 
![image](https://github.com/user-attachments/assets/b19beb10-dcfb-45db-b731-ab3c1ad282e3)

**Comment by samyakmaitre** [comment]
@ayushig05 please work on this

**Comment by samyakmaitre** [comment]
@ayushig05 no response received, handing over to other contributor.

**Comment by Dev-Rishav** [comment]
@samyakmaitre  If this issue is still open, I would like to contribute on it.

**Comment by samyakmaitre** [comment]
issue reolved
