### ISSUE TITLE
Admin Issue | Changes under movies section

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#311]
Requirement: 

![image](https://github.com/user-attachments/assets/146b02b5-1afb-4446-84f7-21505036195d)

**Comment by samyakmaitre** [comment]
@Ankitha2130 Please work on it

**Comment by Ankitha2130** [comment]
Sure

**Comment by samyakmaitre** [comment]
@Ankitha2130 whats the position, please respond, or I will have to assign to someone else.

**Comment by AADESHak007** [comment]
@samyakmaitre if this issue is not being being resolved then I would like to work on it

**Comment by samyakmaitre** [comment]
@AADESHak007 



Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by AADESHak007** [comment]
> @AADESHak007
> 
> Hi there, Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....
> 
> Best regards, Samyak

fine , I will finish this till tomorrow or maybe today

**Comment by AADESHak007** [comment]
Hey @samyakmaitre  I have already completed the task . Please review it
