### ISSUE TITLE
Fevicon not updated to the logo

### ISSUE THREAD

**Issue by YasirKhan231** [samyakmaitre/eventmint#313]
The fevicon is not updated so i change the fevicon of the website and set the logo as fevicon 

![image](https://github.com/user-attachments/assets/6329763a-98c7-4e08-aba6-85174ef1bc7f)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by YasirKhan231** [comment]
Hey please assign this task to me and hactober fest label and you   have close this issue
