### ISSUE TITLE
Add bottom to top button 

### ISSUE THREAD

**Issue by YasirKhan231** [samyakmaitre/eventmint#315]
I am adding an button on the bottom by which when we click on that then we redirect to the top of the webste 

Increase the functionality of the website 
![Screenshot 2024-10-11 183334](https://github.com/user-attachments/assets/b91d8343-08a9-47ab-86dd-1866382046e9)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by YasirKhan231** [comment]
But you have closed this issue so how can i work on this
