### ISSUE TITLE
Rating div not in proper place inside movie details

### ISSUE THREAD

**Issue by SKADE2303** [samyakmaitre/eventmint#316]
The tag which shows the rating of the particular movie is overlapping with the show timings. This could be fixed by changing the layout of the show details page. 
Please assign me this issue. 

Here is a screenshot of the problem
![Screenshot from 2024-10-16 15-55-23](https://github.com/user-attachments/assets/d5c3cbd7-27be-4841-a0a7-8dd6801f7d85)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
