### ISSUE TITLE
Adding 'back to home' option in signin/signup page

### ISSUE THREAD

**Issue by AswaniBolisetti** [samyakmaitre/eventmint#319]
@samyakmaitre 
In the login/signin page, there is no option to go back to home, so I would like to work on this
could you please assing this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
