### ISSUE TITLE
Add a seperate page for each of the Movies Stream ,Events Plays ,Sports Activities, ListYourShow ,Corporates Offers, Gift Cards

### ISSUE THREAD

**Issue by rajlakshmi18704** [samyakmaitre/eventmint#32]
![Screenshot (113)](https://github.com/user-attachments/assets/b9c7d3d0-e3f4-42c4-a53d-8e5127ae703d)
I want to implement the  create the seperate page for each of the different sections  through which user can navigate through to  the dedicated pages for each of the services.

**Comment by Targter** [comment]
I am Abhay Bansal, and I am interested in contributing to your project as part of GSSoC Extended 2024. My focus would be on improving the responsiveness of the webpage and ensuring proper alignment of elements such as boxes, names, and buttons on cards.

Specifically, I would like to:

Make the page fully responsive across different screen sizes.
Align the boxes, names, and buttons on the cards to enhance the overall layout and user experience.


![Screenshot 2024-10-03 151558](https://github.com/user-attachments/assets/61260dc0-a1cd-4c73-ab6e-640d418e28bf)
![Screenshot 2024-10-03 151550](https://github.com/user-attachments/assets/1826ea79-d915-4902-9c55-564d0c332c02)

**Comment by samyakmaitre** [comment]
@rajlakshmi18704 Please go ahead and create PR.
