### ISSUE TITLE
Adding content in Terms of use

### ISSUE THREAD

**Issue by AswaniBolisetti** [samyakmaitre/eventmint#321]
@samyakmaitre 
There is no content available in terms of use option, and also the route is not defined
I would like to work on this
could you please assign this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by AswaniBolisetti** [comment]
@samyakmaitre You closed the issue
