### ISSUE TITLE
Adding content in privacy policy

### ISSUE THREAD

**Issue by AswaniBolisetti** [samyakmaitre/eventmint#322]
@samyakmaitre 
There is no content in privacy policy option too
I would like to work on this
kindly assing this to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
