### ISSUE TITLE
[FEATURE]: Add "Scroll to Top" button and adding descriptive titles for buttons

### ISSUE THREAD

**Issue by ARV0725** [samyakmaitre/eventmint#323]
Hey, I want to add features top the site.
- Like Adding the "Scroll to Top" button to the home page.
- Adding descriptive titles to the buttons of the page when the cursor is hovered on the respective buttons.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
