### ISSUE TITLE
[FEATURE]: "Descriptive Hover Feature"

### ISSUE THREAD

**Issue by ARV0725** [samyakmaitre/eventmint#326]
Hey, @samyakmaitre can you please assign the "Descriptive Hover Feature" task to me.

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
