### ISSUE TITLE
No Navbar in offers page

### ISSUE THREAD

**Issue by Siddhart2004** [samyakmaitre/eventmint#327]
### Description:
The **Offers Page** currently does not have a **navbar**, which impacts navigation and user experience. The navbar is expected to be present on all major pages for consistency.

**Comment by Siddhart2004** [comment]
@samyakmaitre assign this task to me and add relevant labels.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
