### ISSUE TITLE
 Add a "Contact Us" page link 

### ISSUE THREAD

**Issue by Subham1** [samyakmaitre/eventmint#328]
he website has a "Contact Us" link, but it doesn't take users to a working "Contact Us" page. Because of this, users can't find important contact information needed for questions, support, or feedback. Clicking the "Contact Us" link doesn't lead anywhere, which causes confusion

![image](https://github.com/user-attachments/assets/4dc74b12-4fb4-4136-813a-e029dd4a461c)

i want to develop a responsive "Contact Us" page that enhances user experience and ensures accessibility across all devices.

**Comment by Subham1** [comment]
@samyakmaitre could you pls assign me this work under  gssoc label

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
