### ISSUE TITLE
Add FAQs section

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [samyakmaitre/eventmint#330]
Add a FAQs section , it will enhance the user experience.

pls. assign this issue to me , I'll complete it quickly @sanjay-kv

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
