### ISSUE TITLE
Update Scroll Bar for Better User Experience on Event Mint

### ISSUE THREAD

**Issue by aparna-44** [samyakmaitre/eventmint#331]
The current scroll bar on the Event Mint website is fairly standard and could benefit from enhancements to match the overall design of the site. I propose:

Customizing the scroll bar’s color to align with the website’s theme
Implementing smoother scrolling to improve the user experience
Adjusting the size and style for better aesthetics

@samyakmaitre plz assign me this issue , i really want to work on it

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
