### ISSUE TITLE
Cards is not responsive in the home page

### ISSUE THREAD

**Issue by Hemraj-7** [samyakmaitre/eventmint#333]
## Cards is not responsive in the home page, that's looking bad 

![Screenshot 2024-10-16 235713](https://github.com/user-attachments/assets/bcf817d7-33d9-4782-b858-0694d17d4b1f)

### I want to do these card responsive
Assign me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by Hemraj-7** [comment]
> Hi there, Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....
> 
> Best regards, Samyak

Thank You!
