### ISSUE TITLE
Fix NavBar

### ISSUE THREAD

**Issue by suhaniranka006** [samyakmaitre/eventmint#339]
Fixing NavBar will make this website more user friendly , so navbar fixing is needed

**Comment by samyakmaitre** [comment]
try making issue descriptive

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
