### ISSUE TITLE
Sign Up Issue

### ISSUE THREAD

**Issue by suhaniranka006** [samyakmaitre/eventmint#340]
New users are unable to sign up and the issue is arrising as signup failed   i guess there is an issue with database
![eventmintsignup](https://github.com/user-attachments/assets/6eefdead-ff2b-42ca-8dc6-acc82c834d81)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
