### ISSUE TITLE
Enhance README with Project Metrics Table

### ISSUE THREAD

**Issue by neeru24** [samyakmaitre/eventmint#341]
- I would like to propose an enhancement to the README file by adding a table that showcases key project metrics. This will provide visitors with a quick overview of the project's popularity and community involvement.

- Adding contributor pics in the readme.

**Goals:**
- To visually represent the project's growth and engagement metrics.
- To encourage more contributions by showcasing active participation.

**Request:**
Please assign me to this issue, and I will implement the changes to enhance the README file.

**Comment by samyakmaitre** [comment]
move how to contribute area from readme and replace it with your feature.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
