### ISSUE TITLE
Admin Issue | drop down, login button and side menu button enhancement.

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#345]
From this:
![image](https://github.com/user-attachments/assets/288e7ab7-5a63-45cd-9328-0903777570e6)

To this:
![image](https://github.com/user-attachments/assets/fb8d843f-e05f-4569-801c-ad5b63da3d79)

**Comment by Ankitha2130** [comment]
I would like to work on this

**Comment by Dev-Rishav** [comment]
@samyakmaitre If this issue is still open, I would like to contribute on it.

**Comment by samyakmaitre** [comment]
@Ankitha2130 please go ahead
