### ISSUE TITLE
No button to go back when you are on login page

### ISSUE THREAD

**Issue by Anurag519Narula** [samyakmaitre/eventmint#347]
There is no button to go back to home page once you go to signup/signin page. This can negatively impact the user experience in the longer run.

**Comment by Anurag519Narula** [comment]
@samyakmaitre Kindly assign this issue to me and add hacktoberfest label to the issue if you feel this is a genuine issue. Thanks!

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
