### ISSUE TITLE
Improve Footer and Navbar Sections

### ISSUE THREAD

**Issue by Web-Dev-Learner** [samyakmaitre/eventmint#35]
I'd like to improvements to both the Footer and Navbar sections to enhance usability and design consistency across the site.

Could you please add the "label for level" , "Hacktoberfest-accepted" label and "gssoc-ext" label to the issue .

This will ensure my contributions are counted towards Hacktoberfest.

![Screenshot 2024-10-03 113936](https://github.com/user-attachments/assets/deccd792-0d72-4214-b591-77ed87719f32)

![Screenshot 2024-10-03 113954](https://github.com/user-attachments/assets/78795697-f151-40e9-8ad2-c391927b327c)

**Comment by samyakmaitre** [comment]
@Web-Dev-Learner  Footer is managed by another PR, please go ahead with the navbar, try keeping it similar to bookmyshow.

**Comment by samyakmaitre** [comment]
issue resolved already by another PR
