### ISSUE TITLE
Admin Issue | Remove dark/light mode

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#351]
Dark mode do not seem suitable for this kind of webpage.

**Comment by Gauravtb2253** [comment]
pls assign me

**Comment by samyakmaitre** [comment]
Dont forget to remove this effect from every element involved.

**Comment by samyakmaitre** [comment]
issue resolved

**Comment by Gauravtb2253** [comment]
Do you have any specific issue that you can assign me
