### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by madhulika9955** [samyakmaitre/eventmint#352]
in this we can put new logo to this website as this logo is not so intresting and is making thew website  not to attractive with it.
the logo should be in circular or we should use some of the vibrant colours to make it attractive

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
