### ISSUE TITLE
the color of the bottom area should be changed when shifting to dark mode 

### ISSUE THREAD

**Issue by madhulika9955** [samyakmaitre/eventmint#353]
as when the dark mode is switched on then to make some of the contrast change the bootom tabs should get white colur which will make it more attractive and will be attracting the audience.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
