### ISSUE TITLE
Add Scroll back button

### ISSUE THREAD

**Issue by shriyadindi** [samyakmaitre/eventmint#354]
I want add the new feature of scroll back button to the web page.
![image](https://github.com/user-attachments/assets/5b8d7fe7-6f44-4ebd-a4fe-42c30f3bea00)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
