### ISSUE TITLE
No StreamEvents and Plays Page

### ISSUE THREAD

**Issue by Siddhart2004** [samyakmaitre/eventmint#355]
### Description
We need to add two new components to enhance the functionality of our application: **StreamEvents.js** and **Plays.js**.

### Benefits
Adding these components will improve user engagement and provide a more organized interface for viewing events and plays.

**Comment by Siddhart2004** [comment]
@samyakmaitre assign this task to me .

**Comment by samyakmaitre** [comment]
![image](https://github.com/user-attachments/assets/bbc64ac0-6fc1-4444-9fcf-9c196b864861)

Hi there,
I found that StreamEvents.js and Plays.js are just a similar copy of offers.js PFA for reference, I need different UI for each nav options. and therefore cannot merge this PR
