### ISSUE TITLE
Styling of StreamEvents 

### ISSUE THREAD

**Issue by simran0809** [samyakmaitre/eventmint#356]
Styling and layout of StreamEvents i am looking forward to contribute with my styling skills .

Thankyou

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by simran0809** [comment]
I Have already create PR but still not got any labels so today i get PR
and  merged on github
