### ISSUE TITLE
ui enhancement in card section and smooth scroll also some better ui/ux features

### ISSUE THREAD

**Issue by akhileshverma92** [samyakmaitre/eventmint#358]
### Title: UI enhancement in card section and smooth scroll also some better UI/UX features

**Description**:
We need to enhance the UI in the card section and implement smooth scrolling. Additionally, we are looking for other improvements to the overall UI/UX. Here are the key areas that need attention:
- **Card Section Enhancements**: Improve the visual design, layout, and responsiveness of the card elements.
- **Smooth Scroll Implementation**: Ensure smooth scrolling throughout the platform for a better user experience.
- **Additional UI/UX Features**: Identify and implement other UI/UX improvements to enhance the overall user experience.

Would you like to include any additional details or resources for implementation?

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
