### ISSUE TITLE
Add "Forget Password" option in the Login Page

### ISSUE THREAD

**Issue by MohitSrivastava22** [samyakmaitre/eventmint#359]
I will add the Forget password option in the login page so that if any user forget his/her password he/she can easily reset their password through email
![Screenshot (207)](https://github.com/user-attachments/assets/01e9f7dd-063d-4d37-86b7-d87538eb5d8b)

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
