### ISSUE TITLE
Admin Issue | Navbar hover

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#360]
![image](https://github.com/user-attachments/assets/ee83025e-3728-4c71-b0b8-487162de9e72)

1) add hover underline for navbar options.
2) error: static underline for Movie option

**Comment by yr1404** [comment]
Can you please assign me this issue?

**Comment by yr1404** [comment]
Also, please add hacktoberfest label to this issue.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by samyakmaitre** [comment]
issue resolved
