### ISSUE TITLE
🎨 CSS Styling Contest: Style the Sports Activities Page! 🏅

### ISSUE THREAD

**Issue by samyakmaitre** [samyakmaitre/eventmint#361]
Welcome to the *CSS Styling Contest! In this contest, you'll have the opportunity to showcase your CSS skills by styling the **Sports Activities* page. This is your chance to get creative, apply modern CSS techniques, and improve the look and feel of the page! The best design will be *merged* into the project! 🚀

## 📝 How to Participate:
1. Comment on this issue if you're interested. *Only the first 7 people* who comment will be allowed to participate. 🎯
2. Once you've commented, I'll assign you to the issue.
3. You'll have *2 days* to submit your styled version of the Sports Activities page, starting from *Saturday*.
4. Submit your work by creating a pull request (PR) linked to this issue.

## ⚙ What to Do:
- Style the *Sports Activities* page using your best CSS techniques. 🎨
- Edit the `SportsList.css`, `Sport.css`, and `SportsDetails.css `files to change the entire Sports Activities Section.
- Ensure your design is *responsive* and looks great on all devices (desktop, tablet, mobile). 📱💻
- Keep the design *consistent* with the rest of the website's theme. 🖼
  
## ⏰ Deadline:
- The contest starts on *Saturday*  at 12:00 AM IST. ⏳.
- All submissions (PRs) must be submitted by *Sunday* at 11:59 PM IST. ⏳

## 🏆 Prizes:
- The *best design* will be selected and *merged* into the project! 🎉

## 🔥 Rules:
- Only *CSS* changes are allowed. No changes to the HTML or JavaScript.
- Follow the general design guidelines for consistency with the rest of the website.
- Have fun and be creative! 😄

Good luck! May the best design win! 🏅

**Comment by yr1404** [comment]
Hello there,
I would like to participate in this contest. Please assign me this issue under Hactoberfest'24.

**Comment by samyakmaitre** [comment]
@09viv @Aditijainnn @adityakalburgi @alo7lika @Anamika-garg @ananyag309 @Arnab7456 @Arveti-likhitha @AswaniBolisetti @avisha191 @Dev-Rishav @devxMani @Dhruv-Gaba @dipkulkhandelwal21 @Dipu2552003 @Dsmita03 @ezDecode @Gauravtb2253 @Geet2002 @harshbhar0629 @Himanshu-kumar025 @iamendless10 @itbindu @Jashwanth-rit @KiranBaliga @kushal7201 @LifeHashed @mahaveergurjar @Mausumi134 @mehul-m-prajapati @MohdAftab011 @Mujtabaa07 @muskan171105 @neeru24 @Nkovaturient @PulkitShubham @Rahul-AkaVector @riyaaryan2004 @Rohinipilla @rudrapratap63 @sakeel-103 @Sameeratweb @samriddhitiwary @samyakmaitre @saras-69 @saurabh-dev-vns @Sawan-Kushwah @Shariq2003 @shriyadindi @shubhagarwal1 @SKADE2303 @smog-root @Sumanth077s @SupratitDatta @SwanandD121 @ThunderShadows @T-Rahul-prabhu-38 @vanshika704 @Varchasavkr @Varsha567

**Comment by Mausumi134** [comment]
Interested

**Comment by rudrapratap63** [comment]
Intersted

**Comment by mahaveergurjar** [comment]
Intrested

**Comment by Himanshu-kumar025** [comment]
interested

**Comment by neeru24** [comment]
Interested

**Comment by sanchitc05** [comment]
Interested

**Comment by ezDecode** [comment]
Intrested

**Comment by snehas-05** [comment]
Interested

**Comment by PulkitShubham** [comment]
@samyakmaitre Interested .......Kindly assign me this issue

**Comment by Jashwanth-rit** [comment]
@samyakmaitre  interested

**Comment by shriyadindi** [comment]
Interested!

**Comment by kushal7201** [comment]
@samyakmaitre interested

**Comment by itbindu** [comment]
@samyakmaitre Interested

**Comment by Rahul-AkaVector** [comment]
Interested

**Comment by ananyag309** [comment]
Interested

**Comment by Sawan-Kushwah** [comment]
interested

**Comment by samyakmaitre** [comment]
Please note that we are accepting participants until 11:59 PM. Feel free to invite your friends to join this initiative.

**Comment by sakeel-103** [comment]
Interested

**Comment by samyakmaitre** [comment]
Welcome @sakeel-103

**Comment by riyaaryan2004** [comment]
intrested

**Comment by mehul-m-prajapati** [comment]
Intrested 🤚

**Comment by Aditijainnn** [comment]
interested

**Comment by saras-69** [comment]
> @09viv @Aditijainnn @adityakalburgi @alo7lika @Anamika-garg @ananyag309 @Arnab7456 @Arveti-likhitha @AswaniBolisetti @avisha191 @Dev-Rishav @devxMani @Dhruv-Gaba @dipkulkhandelwal21 @Dipu2552003 @Dsmita03 @ezDecode @Gauravtb2253 @Geet2002 @harshbhar0629 @Himanshu-kumar025 @iamendless10 @itbindu @Jashwanth-rit @KiranBaliga @kushal7201 @LifeHashed @mahaveergurjar @Mausumi134 @mehul-m-prajapati @MohdAftab011 @Mujtabaa07 @muskan171105 @neeru24 @Nkovaturient @PulkitShubham @Rahul-AkaVector @riyaaryan2004 @Rohinipilla @rudrapratap63 @sakeel-103 @Sameeratweb @samriddhitiwary @samyakmaitre @saras-69 @saurabh-dev-vns @Sawan-Kushwah @Shariq2003 @shriyadindi @shubhagarwal1 @SKADE2303 @smog-root @Sumanth077s @SupratitDatta @SwanandD121 @ThunderShadows @T-Rahul-prabhu-38 @vanshika704 @Varchasavkr @Varsha567

**Comment by saras-69** [comment]
@samyakmaitre intrested

**Comment by samyakmaitre** [comment]
We are thrilled to welcome @riyaaryan2004 @mehul-m-prajapat @Aditijainnn
Thank you for joining us! We encourage you to start working on your assigned tasks as soon as possible. We’re excited to see your contributions and creativity in action!

**Comment by LifeHashed** [comment]
Interested

**Comment by sanchitc05** [comment]
Hi @samyakmaitre I just wanted to ask you to please check the PR's made to this challenge and declare the winner as soon as possible. We all are very curious to know about the winner 😄
Regards,
Sanchit Chauhan

**Comment by samia-jucse** [comment]
![image](https://github.com/user-attachments/assets/02b88a62-1625-47a3-bbee-3d1510bbc9e4)

I would like to design this card .Please assign me for this

**Comment by samyakmaitre** [comment]
Hello everyone!

A big thank you to all the participants who joined the CSS Styling Contest and brought their creativity to the Sports Activities page! 🙌 We were thrilled to see the talent and hard work you put into making the page look amazing and responsive. 🎨✨

After reviewing all submissions, we're excited to announce the winner! 🎉

🥇 Winner: @yr1404
Congratulations! Your design stood out for its creativity, responsiveness, and seamless integration with the website's theme. Great job! 🚀👏

To everyone else who participated, we genuinely appreciate your contributions. Each of you brought unique design ideas. Keep coding, stay creative, and we hope to see more of your amazing work in the future! 😊💻

Thank you again to everyone who participated, and see you in our next contest!

Regards,
@samyakmaitre , @SwanandD121
