### ISSUE TITLE
Stream Events and Plays Components  

### ISSUE THREAD

**Issue by Siddhart2004** [samyakmaitre/eventmint#364]
# 📋 New Feature Request: Stream Events and Plays Components  

## Description  
We need to add two new components to enhance the functionality of our application: **StreamEvents.js** and **Plays.js**.  

## Benefits  
- **Improves User Engagement:** Provides users with easy access to upcoming events and plays.  
- **Organized Interface:** Offers a structured layout for viewing events and plays, enhancing the overall user experience.

**Comment by Siddhart2004** [comment]
@samyakmaitre added a pr check it out and add relevant lables.

**Comment by samyakmaitre** [comment]
reviewed
