### ISSUE TITLE
improve UI of the Sport activity page cards

### ISSUE THREAD

**Issue by Himanshu-kumar025** [samyakmaitre/eventmint#366]
There is no UI on the Sport activity page cards .I would like to work on this issue under GSSOC'24 and Hacktofest'24 
thank you

![participants](https://github.com/user-attachments/assets/6014bfc6-df73-460f-ac20-c6f3c02f796f)

**Comment by Himanshu-kumar025** [comment]
@samyakmaitre please assign me on this issue.

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
