### ISSUE TITLE
Logo improvement 

### ISSUE THREAD

**Issue by Himanshu-kumar025** [samyakmaitre/eventmint#367]
There is some inconsistencies with the logo . I would like to work on this issue under GSSOC'24 and Hactofest'24.
thank you
![logo](https://github.com/user-attachments/assets/fc8f0cac-f8b0-4ddf-a252-8f48835362f6)

**Comment by Himanshu-kumar025** [comment]
@samyakmaitre  please assign me on this issue

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak


Dark mode is removed, issue reolved.
