### ISSUE TITLE
[BUG] CHATBOT NOT WORKING

### ISSUE THREAD

**Issue by amanver45** [samyakmaitre/eventmint#368]
CHATBOT IS NOT WORKING 
![Screenshot 2024-10-18 185151](https://github.com/user-attachments/assets/5f76f5f0-2de9-446f-aed4-295fe3b0879e)

**Comment by amanver45** [comment]
@samyakmaitre can i work on this issue

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
