### ISSUE TITLE
  Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [samyakmaitre/eventmint#369]
I want to add a page to showcase all the contributors of this website,.
@samyakmaitre can you assign me this issue.

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
