### ISSUE TITLE
site layout and style adjustment in mobile view +eyecatchy scrollbar and progressbar

### ISSUE THREAD

**Issue by srishti023** [samyakmaitre/eventmint#374]
the Whole website look off in mobile view . i want to make it fix it for mobile user's experience .
Also i wa nt to make eyecatchy creative scroll and progress bar that lies with the UI of the website.
![Screenshot (45)](https://github.com/user-attachments/assets/0fe24f36-3f57-4e26-8683-ae1e5cbc6d1c)

please assign me this issue! 
Thankyou!

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
