### ISSUE TITLE
[BUG]: Logo is going outside of the nav bar.

### ISSUE THREAD

**Issue by Adityadhiman0** [samyakmaitre/eventmint#375]
Logo of website is going out side of the nav bar.  It should be within the nav bar.
![Screenshot 2024-10-18 214845](https://github.com/user-attachments/assets/c4a4c0dc-5afd-4645-8e7a-f4684dac2fd1)

**Comment by Adityadhiman0** [comment]
Please assign this issue to me so I can fix it.

**Comment by samyakmaitre** [comment]
issue resolved
