### ISSUE TITLE
ADDITION OF FEEDBACK SECTION✨

### ISSUE THREAD

**Issue by shriyadindi** [samyakmaitre/eventmint#376]
I would like to add a new page for the customer feedback, kindly assign me the task.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by shriyadindi** [comment]
Assign this task to me
