### ISSUE TITLE
[UI]There is a gap inbetween the hero carousel and the main movies suggestions - want to remove that.

### ISSUE THREAD

**Issue by omkar861856** [samyakmaitre/eventmint#377]
# Issue Title: UI enhancement

## Description
[UI]There is a gap inbetween the hero carousel and the main movies suggestions - want to remove that.

## Expected Behavior
carousel and the movie suggestions must be one below the another

## Actual Behavior
gap inbetween the hero carousel and the main movies suggestions

## Screenshots/Logs
<img width="1186" alt="Screenshot 2024-10-18 at 11 25 01 PM" src="https://github.com/user-attachments/assets/be2e185d-22d6-4573-888d-f08ae7ec90ad">

Assign this to me @samyakm

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
