### ISSUE TITLE
Add functionality to help and support  button

### ISSUE THREAD

**Issue by Aditijainnn** [samyakmaitre/eventmint#378]
![image](https://github.com/user-attachments/assets/f72394b0-fa6a-41e9-8c73-d6812743cff3)
in this theese contact us and faq doesnt work so making them working
assign this to me under gssoc ext

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
