### ISSUE TITLE
navbar not sticy

### ISSUE THREAD

**Issue by dipeshkumar799** [samyakmaitre/eventmint#380]
i want to improve your navar while scrolling down the navar hidden.
 i want to makw the  navbar whiole scrolling down the navbar hold on top.

Uploading EventMint and 11 more pages - Personal - Microsoft​ Edge 2024-10-18 22-40-15.mp4…

@samyakmaitre : pls assign me this issue i want to work on that

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by samyakmaitre** [comment]
merged
