### ISSUE TITLE
footer socail icon  color issue

### ISSUE THREAD

**Issue by dipeshkumar799** [samyakmaitre/eventmint#381]
in footer there is icon of facebook ,youtube,instagram...etc
i want to make when we hover in icon the facebook color gonna change in blue and youtube color gonna change in red  .
so,  i make it in real color 
[

https://github.com/user-attachments/assets/517f481b-7c96-470f-8837-1684d74172e5

@samyakmaitre : please aaign me this i  want to work on that.

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
