### ISSUE TITLE
FIX sports cards

### ISSUE THREAD

**Issue by Son7c** [samyakmaitre/eventmint#383]
I would enhance their design and add attractive hovering effects on it please assign this issue to me.

![Screenshot 2024-10-19 133958](https://github.com/user-attachments/assets/a22450a1-2ed3-4cee-a8e5-0942bef04c90)

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned under CSS contest #361 .  We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
