### ISSUE TITLE
add a FAQ Page

### ISSUE THREAD

**Issue by yeshwanth-ds** [samyakmaitre/eventmint#388]
add a responsive FAQ page

**Comment by ChetanSingh14** [comment]
@samyakmaitre assign this issue to me

**Comment by samyakmaitre** [comment]
@yeshwanth-ds 

Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
