### ISSUE TITLE
Feature Request: Add "List Your Show" Page

### ISSUE THREAD

**Issue by pranusri1903** [samyakmaitre/eventmint#390]
## Proposed Feature:

A dedicated page that allows users to:

- List and promote events, performances, gigs, or workshops.
- Provide details about their event (location, date, ticket price, etc.).
- Add images or banners for better visibility.
- Include relevant sections and calls to action such as:
- "Empower the Artist Within" or "Conduct Workshops and More"

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
