### ISSUE TITLE
Feature Request: Add "Gift Cards" Page

### ISSUE THREAD

**Issue by pranusri1903** [samyakmaitre/eventmint#392]
## Description:

It would be beneficial to introduce a "Gift Cards" page on the EventMint platform, similar to what other platforms like BookMyShow offer. This feature will allow users to purchase and gift event tickets or experiences, providing a flexible gifting option that enhances user engagement.

## Proposed Feature:

A dedicated "Gift Cards" page that includes:

- Various gift card options (fixed or customizable values).
- A simple interface to purchase and send gift cards to others.
- Support for digital delivery via email or message.

Add sections like:

- "Corporate Gift Cards" for bulk purchase.
- "Personalized Messages" during gift card purchase.
- Easy redemption instructions for gift card recipients.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
