### ISSUE TITLE
Will add more movie to the website . 

### ISSUE THREAD

**Issue by Abiral-2724** [samyakmaitre/eventmint#393]
Will add more movie to the website , with a page for detail description of each movie .

**Comment by samyakmaitre** [comment]
Hi there,

Add movies in hidden carousel , no new row and columns

Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
