### ISSUE TITLE
[BUG] the chatBot window has no ❌ to exit

### ISSUE THREAD

**Issue by avogadroB** [samyakmaitre/eventmint#395]
the window needs a cross to collapse the window as you need to reload the page to get rid of the chatbot.
Add the cross besides the reload option for easier visibility of users.

![image](https://github.com/user-attachments/assets/584877bd-9c8f-4d59-8791-55f2a7773cd2)

**Comment by avogadroB** [comment]
[samyakmaitre](https://github.com/samyakmaitre) please assign this issue to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by avogadroB** [comment]
thanks!
