### ISSUE TITLE
Add Footer and Enhance UI 

### ISSUE THREAD

**Issue by Mujtabaa07** [samyakmaitre/eventmint#40]
I Finish or Resolve this issue as soon as possible,
With better UI Enhancements ,
Asap

**Comment by Anshika09Singh** [comment]
I also want to solve this issue.

**Comment by simmi-verma** [comment]
I would like to work on it . Please assign to me . Can you add label gssoc-ext 24.

**Comment by samyakmaitre** [comment]
issue resolved
