### ISSUE TITLE
Create "Corporates" page 

### ISSUE THREAD

**Issue by Saaarthak0102** [samyakmaitre/eventmint#405]
# Description

We need to add a new "Corporates" page to the website to display information about partner companies, sponsors, or corporate collaborators. This page should be designed to align with the overall theme and style of the website.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
