### ISSUE TITLE
Revamp movie cards 

### ISSUE THREAD

**Issue by shubhagarwal1** [samyakmaitre/eventmint#406]
<img width="1440" alt="Screenshot 2024-10-21 at 6 48 23 AM" src="https://github.com/user-attachments/assets/0ed0557b-cbd7-4326-82c0-cc154e121442">

**To something like** 
<img width="1437" alt="Screenshot 2024-10-21 at 6 49 15 AM" src="https://github.com/user-attachments/assets/1ecfe05f-ae83-4a98-aff0-b76da82bd16c">

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak

**Comment by shubhagarwal1** [comment]
> Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.
> 
> Looking forward to collaborating again soon.
> 
> Best regards, Samyak

Hey @samyakmaitre can you please tell me something to work on that you have planned or looking to implement 
would love to work on it.
