### ISSUE TITLE
Not responsive.

### ISSUE THREAD

**Issue by Dhruv-Gaba** [samyakmaitre/eventmint#410]
The webpage is not responsive. as shown in the video below. I would like to work on this issue and make the website responsive. Please assign this issue to me.

https://github.com/user-attachments/assets/453078a5-1ca0-42d0-8ee9-5cc42a51539d

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
