### ISSUE TITLE
chatbot not working

### ISSUE THREAD

**Issue by amanver45** [samyakmaitre/eventmint#413]
i want to fix chatbot
![Screenshot 2024-10-21 225207](https://github.com/user-attachments/assets/a2c736cb-677f-489f-b06a-8e5223ed92dc)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
