### ISSUE TITLE
Revamp Your Website: Stylish Navbar Menu for Contributing to an Open-Source Project for a Sleek and Modern Design

### ISSUE THREAD

**Issue by khurshed07** [samyakmaitre/eventmint#416]
# Before Chnages:
![Screenshot 2024-10-22 160626](https://github.com/user-attachments/assets/228435e4-7473-47ea-8a89-e02d7d89b7af)

# After Changes:
![Screenshot 2024-10-22 155842](https://github.com/user-attachments/assets/ff2573a1-3fb7-4131-9a67-da35334fe8e7)
![Screenshot 2024-10-22 155850](https://github.com/user-attachments/assets/b1067d7b-f43a-4936-a6a3-17690400ef8d)
![Screenshot 2024-10-22 155857](https://github.com/user-attachments/assets/e6636ecb-83e0-4655-85b9-ec897a03c521)
![Screenshot 2024-10-22 155903](https://github.com/user-attachments/assets/3dccd0cb-01e1-4df2-9932-f62979a2bbda)
![Screenshot 2024-10-22 155909](https://github.com/user-attachments/assets/513017e0-0bc2-46a1-8bc9-302cad110cd7)
![Screenshot 2024-10-22 155917](https://github.com/user-attachments/assets/b829e9b0-82f9-4411-a293-981b6f552836)
![Screenshot 2024-10-22 155924](https://github.com/user-attachments/assets/0a0d754b-3d6d-445f-b495-1ae6496bd16d)
![Screenshot 2024-10-22 155932](https://github.com/user-attachments/assets/9a2cad21-a93b-4f5a-9d9b-044b1a0b277d)

Hi @samyakmaitre 
I recently updated the navbar menu for your project to make it more attractive and user-friendly. Enhance readability, improve navigation, and give your site a visually appealing touch that stands out with these simple yet impactful design updates. I've attached screenshots of the changes, and I'd love to contribute to this enhancement to improve the overall design.

Please assign me to this task. It would be a great opportunity to contribute while enhancing my skills.

I'm looking forward to hearing back from you!
Best regards,
@khurshed07
https://github.com/khurshed07

**Comment by khurshed07** [comment]
Hi @samyakmaitre
please this issue to me

**Comment by khurshed07** [comment]
Hi @samyakmaitre
please assign this issue to me

**Comment by samyakmaitre** [comment]
Thank you for the updates. While your effort is appreciated, the recent changes seem non-essential and don't add significant value to the project's functionality or user experience.

Regards,
Samyak
