### ISSUE TITLE
Terms and condition section is missing 

### ISSUE THREAD

**Issue by adityalaxkar123** [samyakmaitre/eventmint#419]
Better we add the terms of use the website for better user experience.

Me a GSSOC'24 extended member can you assign it to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. add it under legal footer option. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
