### ISSUE TITLE
Add: Missing Contributing.md

### ISSUE THREAD

**Issue by samyak-aditya** [samyakmaitre/eventmint#42]
### Issue Description: Missing `CONTRIBUTING.md`

**Overview**:  
The repository currently lacks a `CONTRIBUTING.md` file, which is essential for guiding potential contributors on how to effectively participate in the project. This file typically includes instructions on the contribution process, coding standards, and best practices, ensuring that contributions align with the project's goals and maintain quality.

**Proposed Solution**:  
Create a `CONTRIBUTING.md` file that includes the following sections:

1. **Getting Started**: Instructions on how to fork the repository and set up the local development environment.
2. **Code Standards**: Guidelines on coding style, naming conventions, and any specific technologies or frameworks to use.
3. **Submitting Contributions**: Steps for committing changes, creating pull requests, and addressing issues or feedback.
4. **Issue Reporting**: How to report bugs or feature requests effectively.
5. **Community Guidelines**: Expectations for behavior and communication among contributors.

By implementing this file, we can ensure that all contributors have a clear understanding of the process and can collaborate more effectively.

Hey @samyakmaitre Please assign me this task with labels "gssoc-ext", "hacktoberfest-accepted" and "level1"

**Comment by simmi-verma** [comment]
I would like to work on it . Please assign to me . Can you add label gssoc-ext 24.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
can you please add gssoc-ext label

**Comment by samyakmaitre** [comment]
@samyak-aditya Please Go ahead
