### ISSUE TITLE
New Feature: Adding An Event Engagement Dashboard

### ISSUE THREAD

**Issue by diya-kishore** [samyakmaitre/eventmint#420]
The Event Engagement Dashboard offers  analytics and insights for event organizers and participants, enhancing the event experience for schools, colleges, and universities.

**Key Components:**

Organizer Insights:
Track real-time registrations, demographics, and engagement metrics.
Access audience feedback and social media interactions.
Participant Engagement:
personalized dashboard for attendees to view registered events and recommendations.
Interactive polls and feedback options during events.

**Networking Opportunities:**

Attendee networking features and mentorship matches to foster connections.

**Gamification Elements:**

Achievements and badges for participation, along with a leaderboard to encourage engagement.
Post-Event Analytics:
Detailed impact reports and participant surveys for feedback and improvement.

**Benefits:**
Increases efficiency for organizers and boosts participant engagement.
Facilitates networking and collaboration within the community.
This feature will provide valuable insights and enhance the overall event experience, differentiating your platform from traditional registration systems.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
