### ISSUE TITLE
changing the signup page ui 

### ISSUE THREAD

**Issue by REHAN-18** [samyakmaitre/eventmint#421]
signup page ui is so dull can make better sign up page also integrate login with iOS which enhances the website login credibility..

**Comment by REHAN-18** [comment]
<img width="1146" alt="Screenshot 2024-10-23 at 2 50 38 PM" src="https://github.com/user-attachments/assets/baeefa8c-68b3-41bb-90cd-3b5b64778305">
is looking to old design

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by REHAN-18** [comment]
@samyakmaitre ok sir !!! but ur closing this issue ??
