### ISSUE TITLE
Bug: Social Media Icons Not Functioning

### ISSUE THREAD

**Issue by RachitSahu26** [samyakmaitre/eventmint#422]
The social media icons (Facebook, Instagram, and LinkedIn) located in the footer/header of the platform are currently non-functional. When users click on these icons, there is no response or redirection to the respective social media pages.

Steps to Reproduce:

Navigate to the footer/header of the platform.
Click on the Facebook, Instagram, or LinkedIn icons.
Observe that there is no action taken or page redirection.
Expected Behavior:
Clicking on the social media icons should redirect users to the respective platforms' pages (e.g., Facebook, Instagram, LinkedIn).

Actual Behavior:
Currently, the icons do not perform any action when clicked.

Suggested Fix:
Verify the links associated with each icon and ensure they are correctly set up to open in a new tab or redirect to the appropriate social media pages

**Comment by RachitSahu26** [comment]
please assign this issue to me i would like to work on it and make it more attractive as you say @samyakmaitre

**Comment by samyakmaitre** [comment]
We currently dont have any, so currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
