### ISSUE TITLE
BUG-Prevent Horizontal Scroll Overflow

### ISSUE THREAD

**Issue by RishabxBhardwaj** [samyakmaitre/eventmint#423]
The page is experiencing an overflow issue where content exceeds the viewport width, causing unintended horizontal scrolling. This issue is more noticeable on smaller screens or mobile devices. The likely causes could be:

Elements with fixed widths that exceed the viewport size.
Long text or images without responsive behavior.
Incorrect use of margins, padding, or CSS properties like overflow.

assing me the problem i can fix it

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
