### ISSUE TITLE
[bug] the social media icons just take you to the top of the page 💡

### ISSUE THREAD

**Issue by avogadroB** [samyakmaitre/eventmint#424]
Instead, just redirect them to the social media sites' homepage or any other handles that you can provide me. 
![image](https://github.com/user-attachments/assets/61f7c932-de40-457d-8aa9-74de803bfc81)

@samyakmaitre I would like to work on this issue

**Comment by samyakmaitre** [comment]
We currently dont have any, so currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
