### ISSUE TITLE
[Add functionality] Add a tail to the mouse for the website for a better UI

### ISSUE THREAD

**Issue by avogadroB** [samyakmaitre/eventmint#425]
Add a circular tail to the entire website for a better Mouse tracking and UI

I would like to work on this issue. please assign this to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
