### ISSUE TITLE
Adding Docker file to the Project

### ISSUE THREAD

**Issue by spc-28** [samyakmaitre/eventmint#427]
For having a simpler local development setup we can add a docker-yaml file.
Please assign this issue to me.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
