### ISSUE TITLE
enhance security by rate limit to login api

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#428]
i want to add a rate limiter to the login api 
advantages:
prevent bots brute force attack
enhance security
reduce load on api

please assign this issue to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
