### ISSUE TITLE
sign in with google i doesnt work

### ISSUE THREAD

**Issue by JagritiChopra** [samyakmaitre/eventmint#429]
![Screenshot (206)](https://github.com/user-attachments/assets/f12888d7-9e22-4150-bdb8-d4221666ebcd)

Can you assign this to me under gssoc tag?

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
