### ISSUE TITLE
Theme change option addtion

### ISSUE THREAD

**Issue by JagritiChopra** [samyakmaitre/eventmint#430]
![Screenshot (207)](https://github.com/user-attachments/assets/6954d422-4ea6-4a86-8229-43024725c91d)

No option for theme change 
Can you assign this to me under gssoc tag?

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
