### ISSUE TITLE
Account and setting option does not opens any page

### ISSUE THREAD

**Issue by JagritiChopra** [samyakmaitre/eventmint#431]
![Screenshot (207)](https://github.com/user-attachments/assets/8de59c52-67ff-40e7-b978-ab9f5dd64bd1)

Issue Descripton:
The account and setting option on homepage doesnot opens any page .I wish to fix this

Can you assign this to me under gssoc tag

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
