### ISSUE TITLE
The chatbot is not working !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [samyakmaitre/eventmint#434]
![image](https://github.com/user-attachments/assets/12d96a33-fd11-453f-b0a2-2fea743a0384)

@samyakmaitre , please assign me under this issue , i will fix it

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
