### ISSUE TITLE
Login page UI Alignment Issue 

### ISSUE THREAD

**Issue by sujeet9682** [samyakmaitre/eventmint#435]
## Description: 
There is an inconsistency in the alignment of login page UI image and form, causing one side of the UI to appear upper. This misalignment seeking attention instantly. It would also be better if form will be on right side and image be on left.

## Steps to Reproduce:
1. Open the application.
2. Navigate to login section.
3. Observe the alignment of elements on both sides of the screen.

## Currently

<img width="1459" alt="Screenshot 2024-10-26 at 8 54 28 AM" src="https://github.com/user-attachments/assets/cf491cbe-eed8-403c-b4d6-91d1712464b0">

Please assign this issue to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
