### ISSUE TITLE
bug:navbar is not responsive 

### ISSUE THREAD

**Issue by sujeet9682** [samyakmaitre/eventmint#436]
## Description
The navbar is currently breaking on small screens. The elements are misaligned, and the navbar lacks proper responsiveness, affecting the user experience.

## Steps to Reproduce
minimize the website as small screen 
Observe the navbar’s layout and alignment of elements.

https://github.com/user-attachments/assets/2160cfc9-d95a-4118-acab-a68a6f508593

## Expected Behavior
The navbar should adjust to smaller screen 
## Aligning elements correctly.
Becoming fully responsive without breaking or causing overflow issues.
and hero carousel should properly adjusted.

Please assign this issue to me.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
