### ISSUE TITLE
Add Dark Mode to Website

### ISSUE THREAD

**Issue by T-Fathima** [samyakmaitre/eventmint#437]
**Description:**
Implement a dark mode feature for the website to improve user experience, particularly in low-light environments.
Add a toggle switch in the header or settings for users to switch between light and dark mode.
Ensure that colors, text, buttons, backgrounds, and other UI elements adapt smoothly when toggling between modes.
Use CSS variables to define color themes, making it easier to maintain and adjust colors.

@samyakmaitre I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
