### ISSUE TITLE
Add Table of Contents in the readme file

### ISSUE THREAD

**Issue by T-Fathima** [samyakmaitre/eventmint#438]
I would like to add the table of contents for the readme file to enhance the readability and better navigation.
@samyakmaitre I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
