### ISSUE TITLE
The options at the bottom of the page doesn't close when clicking away

### ISSUE THREAD

**Issue by ayush-343** [samyakmaitre/eventmint#439]
**Description:**

When clicking outside the drop-down box it doesn't close, causing them to stay open even when opening other options.

**Video:**

https://github.com/user-attachments/assets/bf6674e2-096e-4a72-bbf1-58b5a68b33c9

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
