### ISSUE TITLE
proper allignment

### ISSUE THREAD

**Issue by kashishchadha** [samyakmaitre/eventmint#44]
Actually their is problem in code ,there is no proper allignment in the code not properly spaced ,some are above and some things are below ,i will correct all this ..
assign this to me and add labels to this ,i will give a proper layout to it and fix the entire code ..i have already worked in such projects so please assign this to me

**Comment by samyakmaitre** [comment]
Please ahead.

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
