### ISSUE TITLE
bug:All right ,terms of use and privacy policy are not properly aligned 

### ISSUE THREAD

**Issue by samia-jucse** [samyakmaitre/eventmint#440]
![image](https://github.com/user-attachments/assets/e653fca8-f05d-4ab3-9235-97686b54cfaa)
i want to work with this problem.Please assign me.

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
