### ISSUE TITLE
Bug: The slider images exceeding the page in the x direction

### ISSUE THREAD

**Issue by Durgeshwar-AI** [samyakmaitre/eventmint#441]
![Screenshot 2024-10-27 113434](https://github.com/user-attachments/assets/d7bce81c-e6df-4db3-b1d9-01ef766890d5)
As seen in the picture i would like to correct that.

**Comment by JOSHITHA6** [comment]
Please assign this task to me @samyakmaitre under gssoc'24 extd and hacktoberfest'24

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
