### ISSUE TITLE
about the Sign in and Login Button

### ISSUE THREAD

**Issue by sachinggsingh** [samyakmaitre/eventmint#442]
![Screenshot 2024-10-27 130812](https://github.com/user-attachments/assets/5b5b25df-ab9a-487a-8dce-6b4bcae64ed8)
The text is Over Flown From the button

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been resolved by  another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
