### ISSUE TITLE
In the Hamburger section

### ISSUE THREAD

**Issue by sachinggsingh** [samyakmaitre/eventmint#443]
![Screenshot 2024-10-27 130800](https://github.com/user-attachments/assets/6c21b63f-e8a4-4768-9488-61a047974832)
The Close button of the hamburger is coming on the Text

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by JOSHITHA6** [comment]
Kindly assign me this issue under gssoc'24 extd and hacktoberfest'24 @samyakmaitre

**Comment by samyakmaitre** [comment]
@sachinggsingh 
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
