### ISSUE TITLE
Improper formatting of pictures inside sports activities section

### ISSUE THREAD

**Issue by JOSHITHA6** [samyakmaitre/eventmint#444]
I have found that the picture of a particular sport has merged with the header, which gives a bad UI experience as a user. Kindly assign this task to me under gssoc'24 extd and hacktoberfest'24

![Screenshot (229)](https://github.com/user-attachments/assets/97431b53-dc06-407e-82db-c3a1d977b04f)

In this screenshot, the swimming picture has been merged with the header which looks very poor in quality.

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
