### ISSUE TITLE
implementation contact Page and FAQ 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [samyakmaitre/eventmint#447]
A dedicated contact page shows that your business is open to communication, making users feel more comfortable reaching out. This transparency can help establish trust.

Users know where to go if they need assistance, whether they have questions, need support, or want to give feedback, improving overall satisfaction.

An FAQ page allows users to find answers to common questions quickly, reducing the need to contact support for basic inquiries, which improves the overall experience.

FAQ pages are often rich with keywords related to your business and can drive organic traffic. Users searching for answers may land on your page, enhancing visibility in search engines.

**Comment by RahulPrasadYadav** [comment]
@samyakmaitre assign the issue .. need to work

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by RahulPrasadYadav** [comment]
@samyakmaitre okey
