### ISSUE TITLE
Add facbook and X button in login page and sign page 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [samyakmaitre/eventmint#448]
![Screenshot (445)](https://github.com/user-attachments/assets/41a403de-3374-4f6b-932f-185e799c4a96)
Facebook login provides a quick way for users to sign up without creating new usernames and passwords, reducing friction during registration.

Many users are more likely to register if they see a familiar login option like Facebook, which can lead to higher sign-up rates, especially among those who may otherwise abandon the process.

**Comment by RahulPrasadYadav** [comment]
@samyakmaitre assign the issue

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
