### ISSUE TITLE
remove unused dependencies

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#453]
![image](https://github.com/user-attachments/assets/7cceba2d-8022-40e6-a574-72461296b63f)

i want to remove these unused dep 

please assign this issue to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
