### ISSUE TITLE
forgot password bug

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#454]
the forgot password form send email to all the emails which request forgot password request 
but 
1) it must first check that whether the email exiist in the database
2) if yes send email
3) if not give a message that the user do not exist 

because the email password reset link is of no use for the person who is not a user already

also there is not loading when the user clicks send button and no proper feeback i will add both and also add a functionality in the backend of checking user before sending mail

please assign this  issue to me @samyakmaitre 

![image](https://github.com/user-attachments/assets/e23a8336-7885-4b1a-b0e5-becb70ba2030)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
