### ISSUE TITLE
Lack of css in the index.html page

### ISSUE THREAD

**Issue by JOSHITHA6** [samyakmaitre/eventmint#455]
I have noticed that there's no CSS applied for the index page, giving the user a dull look. Kindly assign this to me under gssoc'24 extd and hacktoberfest @samyakmaitre 

![Screenshot (243)](https://github.com/user-attachments/assets/0d6fb242-7d87-4e2f-b32a-93449674907a)

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
