### ISSUE TITLE
I want to add voice search functionality to the website

### ISSUE THREAD

**Issue by Sambashivarao-Boyina** [samyakmaitre/eventmint#457]
I have a an idea to add the voice search functionality to the website.

so users can able to search with voice who are not able to type the message.

![Screenshot from 2024-10-28 15-57-00](https://github.com/user-attachments/assets/24f017d0-4f44-4b41-bd17-41cc10fd4957)

I Can implement this. I have already implemented in my projects. 

Please assign this to me. let me contriunte to this project under **gssoc-ext**, **hacktoberfest2024**

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
