### ISSUE TITLE
No content added for Terms of Use and Privacy Policy

### ISSUE THREAD

**Issue by AswaniBolisetti** [samyakmaitre/eventmint#460]
@samyakmaitre 
In the footer, Terms of Use and Privacy policy options are there, but no content is provided
I would like to work on it
Kindly assign it to me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
