### ISSUE TITLE
Bug : Carousel slider causing unwanted overflow during slide transition 

### ISSUE THREAD

**Issue by sujeet9682** [samyakmaitre/eventmint#464]
## Description

Noticed that unwanted space is appearing while sliding the carousel from blank space present below the slider. This affects the layout and user experience, as the page displays unwanted overflow occur from the screen.

https://github.com/user-attachments/assets/55d46df1-3e77-42af-a664-54a263f31767

### Steps to Reproduce

1. Go to the page with the carousel slider.
2. Slide the screen toward right
3. Observe the blank space that appears

Expected Behavior: The carousel should slide smoothly without displaying any extra space or overflow.

--
Please assign this issue to me.

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak
