### ISSUE TITLE
BUG : Overflow in x-direction of the website 

### ISSUE THREAD

**Issue by AADESHak007** [samyakmaitre/eventmint#465]
The website is overflowing in the `x-direction` which I probably think is a development bug .
This is should be resolved .
I want to resolve this bug  .
Please assign this issue to me  .
#### Screenshots : 
![Screenshot 2024-10-28 173440](https://github.com/user-attachments/assets/55f5f140-a051-4cca-9e29-fa613e5061e1)

**Comment by samyakmaitre** [comment]
issue resolved
