### ISSUE TITLE
stream-events is not visable

### ISSUE THREAD

**Issue by RAMIREDDYGAYATHRI02** [samyakmaitre/eventmint#467]
while clicking the stream-events button it will redirect to that route in url but not displayed anything!
![Screenshot (1462)](https://github.com/user-attachments/assets/c4716363-eeb9-4b69-8f0c-a06a4fd3a8fe)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
