### ISSUE TITLE
[feat] Redesign the login page 

### ISSUE THREAD

**Issue by REHAN-18** [samyakmaitre/eventmint#469]
this login  page is not suits the this good looking website 
I want to redesign it change the ui of the signup page with modern style signup which enhances the website ui
<img width="1160" alt="Screenshot 2024-10-29 at 6 27 04 PM" src="https://github.com/user-attachments/assets/e642bba0-9e7c-4a79-9b8d-7e2a37bd56fa">

**Comment by REHAN-18** [comment]
@Sameeratweb sir pls assign me under level 3 if possible

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by REHAN-18** [comment]
@samyakmaitre sir you ve close the issue how I can go ahead and resolve issue !!

> Hi there, Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....
> 
> Best regards, Samyak

**Comment by samyakmaitre** [comment]
By mistake

**Comment by REHAN-18** [comment]
@samyakmaitre ok sir !! can I start or not??

**Comment by REHAN-18** [comment]
> create your PR, I will accept

@samyakmaitre sir can I remove the login /signup img????

**Comment by REHAN-18** [comment]
> create your PR, I will accept

pls reply asap I m working on this !!

**Comment by REHAN-18** [comment]
@samyakmaitre can I remove template.jsx if I'm removing the imp because there Is no sense in the template  direct we make login/sign up page ???

pls reply asap I start working on this then

**Comment by REHAN-18** [comment]
@samyakmaitre sir say>????
