### ISSUE TITLE
Change the tab name from React App to BookmyShow

### ISSUE THREAD

**Issue by PraveenUppar** [samyakmaitre/eventmint#47]
## Isssue
The existing tab name is React App it can be changed to BookmyShow for better user experience
## Screenshot
![Screenshot 2024-10-04 113116](https://github.com/user-attachments/assets/d05d29c4-0742-4448-af94-ad6786791923)

**Comment by komalnalage** [comment]
I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute .

Thanks so much!

**Comment by samyakmaitre** [comment]
Issue already resolved by another PR.
