### ISSUE TITLE
BUG -> UI overlap in home page

### ISSUE THREAD

**Issue by Gauravtb2253** [samyakmaitre/eventmint#471]
Hello
In the home page image slider, the circles of the slider are not fully visible and overlap with bottom UI

![image](https://github.com/user-attachments/assets/a35c4c0c-ba44-4750-8803-a7eebfa201b7)

I would like to solve it
Pls assign me

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by Gauravtb2253** [comment]
do you have more issues to solve
