### ISSUE TITLE
movies page is not visible

### ISSUE THREAD

**Issue by sujeet9682** [samyakmaitre/eventmint#472]
---
#####  while clicking the movies button it will redirecting to that route in url but not displayed anything!

<img width="1582" alt="Screenshot 2024-10-30 at 12 54 53 PM" src="https://github.com/user-attachments/assets/0af80b54-439c-4dae-8c6f-1412a7aaa5ca">

**Comment by samyakmaitre** [comment]
Movies page is not created, you can work on it if you want, create PR I will review and accept

**Comment by sujeet9682** [comment]
Thanks.
Sure, i am creating a movie page
