### ISSUE TITLE
Navigation option need to be present on every page

### ISSUE THREAD

**Issue by sujeet9682** [samyakmaitre/eventmint#473]
## Description 

- There is no navigation option on Offers page and List your show page 
- The route /Corporates doesn’t able display the expected component

<img width="1582" alt="Screenshot 2024-10-30 at 1 58 53 PM" src="https://github.com/user-attachments/assets/cd947d92-30fc-43b2-8c7d-8046d3440e2d">
<img width="1582" alt="Screenshot 2024-10-30 at 1 59 03 PM" src="https://github.com/user-attachments/assets/09b87ffe-f959-4b25-90e9-2c27cd960b1b">
<img width="1582" alt="Screenshot 2024-10-30 at 1 58 36 PM" src="https://github.com/user-attachments/assets/1d740157-e030-4f34-87ad-b8644f5d6f88">

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

add header and navbar as on homepage

**Comment by sujeet9682** [comment]
Every page in your application contains footer also. I will attach the footer if you agree
