### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by jainaryan04** [samyakmaitre/eventmint#475]
Implementing dark mode improves user comfort by reducing eye strain and glare, especially in low-light environments. It enhances readability, conserves battery on OLED devices, and aligns with modern design practices. Supporting dark mode will offer a better user experience and accessibility, catering to diverse user preferences.

**Comment by jainaryan04** [comment]
@samyakmaitre

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
@samyakmaitre
