### ISSUE TITLE
Use TMDB public API to fetch movies dynamically

### ISSUE THREAD

**Issue by mehul-m-prajapati** [samyakmaitre/eventmint#476]
- Currently, we are showing static movies from search bar
- We can use TMDB public API get searched movie details

![t1](https://github.com/user-attachments/assets/45f457bf-527e-422c-8322-bb8a02ef95fd)

**Comment by mehul-m-prajapati** [comment]
@samyakmaitre : are you active for this repo?

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by mehul-m-prajapati** [comment]
@samyakmaitre : please re-open issue with labels
