### ISSUE TITLE
create backend to list your show

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#477]
currently there is no backend for this page 
![image](https://github.com/user-attachments/assets/ddcb1022-b9fe-4736-9066-0a2e037ea87f)

i will create  backend and ensure that the data is inserted in the database on button click 

also i will add loader and notification when the api is processing data for posting to database

please assign this issue to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
