### ISSUE TITLE
Adding Slider to Movie section so that they automatically move from left to right 

### ISSUE THREAD

**Issue by HetuKariya** [samyakmaitre/eventmint#481]
Please Assign me this issue and also gssoc-ext tag too

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
