### ISSUE TITLE
Adding an AI generated page for picking movies based on your taste for the website.

### ISSUE THREAD

**Issue by shriyadindi** [samyakmaitre/eventmint#482]
Adding an AI generated page for picking movies based on your taste for the website.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak

**Comment by shriyadindi** [comment]
@samyakmaitre You've closed the issue, assign me the issue to work on it.

**Comment by samyakmaitre** [comment]
create PR I will accept
