### ISSUE TITLE
Social sharing option

### ISSUE THREAD

**Issue by Subashree-selvaraj** [samyakmaitre/eventmint#483]
I would like to add social sharing option to eventmint platform.which enables user to share the platform in various media

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
