### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by kushwxha** [samyakmaitre/eventmint#485]
hey @samyakmaitre,
i would like to add issue template to the repo so i would be easy for contributors to create new and descriptive issues.
so that anyone can understand issue easily.
can you please assign it to me? i would like to work on it.

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
