### ISSUE TITLE
keep the navigation bar to list my show page

### ISSUE THREAD

**Issue by avogadroB** [samyakmaitre/eventmint#486]
![image](https://github.com/user-attachments/assets/a4239d64-999d-4300-805a-fb00c13380f0)

![image](https://github.com/user-attachments/assets/d5ceca6b-3b98-4c45-b7fc-63503f01235b)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
