### ISSUE TITLE
Add google maps API to be able to choose current location 📍

### ISSUE THREAD

**Issue by avogadroB** [samyakmaitre/eventmint#487]
![image](https://github.com/user-attachments/assets/46b49f6c-0e71-4882-9893-ea89a84a0def)

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the su
/ggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
