### ISSUE TITLE
Stay Connected

### ISSUE THREAD

**Issue by haseebzaki-07** [samyakmaitre/eventmint#489]
I want to add the implementation for stay connected so that the user entering their mail ids receive a Confirmation mail on their valid mail ids saying thank you!

![Uploading Screenshot 2024-11-03 003046.png…]()

**Comment by satyam969** [comment]
well i can use emailjs to do so but after 100 mails it will be paid and u will be only required to make a account there

**Comment by haseebzaki-07** [comment]
Will be done using nodemailer

**Comment by samyakmaitre** [comment]
@haseebzaki-07 
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
