### ISSUE TITLE
add a custom 404 page with animations

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#491]
right now any route which is not present shows blank page i want to add a custom 404 page for the website

![image](https://github.com/user-attachments/assets/5c37143e-20d0-4164-95e3-e1d89964eefd)

please assign this issue to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
