### ISSUE TITLE
[feat] Redesign the login page 

### ISSUE THREAD

**Issue by REHAN-18** [samyakmaitre/eventmint#493]
this login page is not suits the this good looking website
I want to redesign it change the ui of the signup page with modern style signup which enhances the website ui

@samyakmaitre sir pls assign me under level 3 if possible

**Comment by veepanshu-kasana** [comment]
@samyakmaitre I want to contribute to this project on this particular issue. Please assign it to me!

**Comment by AryanSingh1112** [comment]
@samyakmaitre please assign it to me

**Comment by samyakmaitre** [comment]
@REHAN-18 

Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
