### ISSUE TITLE
More Details button alignment issue!

### ISSUE THREAD

**Issue by veepanshu-kasana** [samyakmaitre/eventmint#494]
![issue](https://github.com/user-attachments/assets/7010f837-23c9-46d4-be94-f951485e140f)

@samyakmaitre I want to align more details button to left as it doesn't look appealing and seems miss-aligned shifted towards right not in the center. Please assign it to me!

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak
