### ISSUE TITLE
send email when newsletter is subscribed

### ISSUE THREAD

**Issue by AyushSharma72** [samyakmaitre/eventmint#497]
![image](https://github.com/user-attachments/assets/412f59ed-6701-440d-a5d3-7b8462cd7f08)

right now no email is sent when the newsletter is subscribed i will add an api which send email to the user upon news letter subscribtion

for eg like this:
![Screenshot (121)](https://github.com/user-attachments/assets/f50d03c5-1896-42b1-9c34-40da2d46890c)

please assign this issue to me @samyakmaitre

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
