### ISSUE TITLE
Scroll to top button is not showing

### ISSUE THREAD

**Issue by souvikpramanikgit** [samyakmaitre/eventmint#498]
Because of the chatbot the scroll to top button is not showing, so i want to move the scroll to top button to the left side of the chatbot button.

**Comment by samyakmaitre** [comment]
Hi there,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Please sync fork and then work on your issue. Don't forget to connect on Github....

Best regards,
Samyak
