### ISSUE TITLE
More Effective Footer Section Can be made

### ISSUE THREAD

**Issue by Sameeratweb** [samyakmaitre/eventmint#5]
We can enhance the effectiveness and appealing design of the footer section by improving the layout organization and ensuring user-friendly navigation.

I would Like to work on this please allow me with labels and Issues .

GSSoC'24-Extd | Contributor

**Comment by samyakmaitre** [comment]
Please go ahead

**Comment by Divyansh2992** [comment]
i want to make contribution in it.

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
