### ISSUE TITLE
Want to make Movie Card responsive as content is hidden

### ISSUE THREAD

**Issue by AkankshaSinghK** [samyakmaitre/eventmint#51]
@samyakmaitre 

I would like to improve the user experience by making the movie card responsive, as some of the content is currently hidden. This will ensure that all information is accessible and visually appealing across different screen sizes and devices.

![image](https://github.com/user-attachments/assets/d01d0e08-e290-4af9-9fab-1b4ad77a6465)

Kindly assign this issue to me and add gssoc-extd and hactoberfest tag and level it.

**Comment by samyakmaitre** [comment]
Please go ahead.

**Comment by AkankshaSinghK** [comment]
@samyakmaitre please add gsssoc-extd and hactoberfest-accepted tag and level it.

**Comment by samyakmaitre** [comment]
I will surely add them while merging DW.

**Comment by samyakmaitre** [comment]
merged

**Comment by AkankshaSinghK** [comment]
Have you added gssoc labels
