### ISSUE TITLE
Proposal : Creating Sign In Sign Up pages

### ISSUE THREAD

**Issue by AbhijitMotekar99** [samyakmaitre/eventmint#52]

**Comment by komalnalage** [comment]
Hey there! I’d love to contribute by designing and developing the sign-in and sign-up pages for the platform. I believe having clean, user-friendly authentication pages is crucial for creating a smooth first impression. I’ll ensure the design is intuitive, secure, and visually appealing, keeping user experience in mind.

Could you please assign me this task under the GSSOC and Hacktoberfest tags? I’m excited to get started and help enhance the platform!

Thanks a lot!

**Comment by samyakmaitre** [comment]
Issue already assigned under #38
