### ISSUE TITLE
Footer need more UI/UX and features

### ISSUE THREAD

**Issue by Harshgupta88156** [samyakmaitre/eventmint#54]
![Screenshot 2024-10-04 200721](https://github.com/user-attachments/assets/b3faa849-dd25-43a6-8b3e-f072b36dd5f2)
This footer looks more simple and need more interaction!!!

assign me this issue i will fix it!!

**Comment by komalnalage** [comment]
Hi @samyakmaitre  I would like to work on this issue  Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!

**Comment by samyakmaitre** [comment]
Issue already mentioned and assigned under #41
