### ISSUE TITLE
Add footer as well as enhancing the UI of the website.

### ISSUE THREAD

**Issue by Dsmita03** [samyakmaitre/eventmint#56]
i would like to improve the ui of the website as well as i want to improve the footer design.

**Comment by samyakmaitre** [comment]
Issue already assigned earlier, kindly try working on replacing logo from "bookmyshow" to one from src folder.

**Comment by Dsmita03** [comment]
okayy

**Comment by samyakmaitre** [comment]
Create a PR and mention #56

**Comment by samyakmaitre** [comment]
merged
