### ISSUE TITLE
Add Dark Mode theme to website making it more interactive.

### ISSUE THREAD

**Issue by Deepika14145** [samyakmaitre/eventmint#57]
Adding a Dark mode theme to this website will make this website more interactive and attractive. 

Issue:
The website looks simple with mono-color with single background color.

Solution:
I will simply add a Dark theme to this website and will make sure that users will be able to switch in which theme they want to view this website, for that I will add a Button. 

Benefit:
Users can switch between the Dark theme and the light theme as per convenience.

![Screenshot 2024-10-04 234314](https://github.com/user-attachments/assets/39b6c1a8-6df1-4036-b7a3-69f186e27749)

Before diving:
1) I will make sure any implementation details are not altered.
2) I have read the readme file to avoid any mistakes.

Please assign me this task @samyakmaitre, @Nkovaturient, @Geet2002. I will do my best to contribute to this website.
Add Labels GSSoC-Extd | Hactoberfest-accepted | Labels as per your convenience.

**Comment by samyakmaitre** [comment]
Please go ahead. create PR once done.

**Comment by Deepika14145** [comment]
Thank you so much for assigning me the task. I will work on it and give you updates. Please add labels GSSoC-Extd | Hactoberfest-accepted | Labels.

**Comment by Deepika14145** [comment]
Okay I will give you updates soon @samyakmaitre

**Comment by Deepika14145** [comment]
Hey @samyakmaitre I'm done with my task I will create PR soon.
