### ISSUE TITLE
Adding rate us option

### ISSUE THREAD

**Issue by Aditijainnn** [samyakmaitre/eventmint#59]
in the bottom or top adding rate us option for better user interaction 
please assign this to me under gssoc ext and Hacktoberfest

**Comment by samyakmaitre** [comment]
Please proceed with the necessary work, but do not create a Pull Request until I give my confirmation.

**Comment by Aditijainnn** [comment]
> Please proceed with the necessary work, but do not create a Pull Request until I give my confirmation.

ok

**Comment by Aditijainnn** [comment]
@samyakmaitre please reopen this issue i am working on it

**Comment by samyakmaitre** [comment]
issue resolved
