### ISSUE TITLE
doc: update README with installation instructions

### ISSUE THREAD

**Issue by Nkovaturient** [samyakmaitre/eventmint#6]
Hello there! @samyakmaitre , 

In order to help developers to feasibly navigate through your repository and make necessary changes  along with rendering  a innovative, eye-catchy outlook to the README, I would propose to revamp README.md file with

-  installation instructions, 
- contributions guidelines,
- contact & support section

Could you please assign me this issue under GSSOC'24 extd?

**Comment by iamsaura8h** [comment]
@samyakmaitre  assign me this issue so i can update the documnetation with images

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
can you please add gssoc-ext label

**Comment by samyakmaitre** [comment]
Issue already resolved by another PR.
