### ISSUE TITLE
BUG : buttons are not responsive

### ISSUE THREAD

**Issue by Anshuaman2001** [samyakmaitre/eventmint#61]
buttons are not responsive they are not positioned properly.
![Screenshot 2024-10-05 041234](https://github.com/user-attachments/assets/e7e64f60-4227-4cbb-ac47-a17531c943a1)

**Comment by Anshuaman2001** [comment]
gssoc extended 2024 and hactoberfest contributor

**Comment by samyakmaitre** [comment]
Please go ahead.
