### ISSUE TITLE
improve image quality

### ISSUE THREAD

**Issue by vijaychandra1910** [samyakmaitre/eventmint#63]
![Screenshot 2024-10-05 161622](https://github.com/user-attachments/assets/27d1cf76-c0f0-4cf8-850f-fddfbe4403a5)

Improve the quality of image for the user interaction.

![Screenshot 2024-10-05 161729](https://github.com/user-attachments/assets/176ce7c8-274d-4d29-977c-77d27585264a)
Make this button clickable with hover effect 
also add see more details where user can explore more details about the movies like actor, director, release data etc.

**Comment by samyakmaitre** [comment]
Please go ahead.

**Comment by GoelManan10** [comment]
I would like to work on this! Can you please assign me this.
