### ISSUE TITLE
Event page

### ISSUE THREAD

**Issue by Dsmita03** [samyakmaitre/eventmint#67]
<img width="1440" alt="Screenshot 2024-10-05 at 11 12 14 PM" src="https://github.com/user-attachments/assets/2505249d-ebe2-490a-8fb0-c6b4b0b33a97">
i will make similar event page of bookmyshow for this website eventmint.
Please assign me this task.

**Comment by samyakmaitre** [comment]
Please Go ahead.

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
