### ISSUE TITLE
(Simple Feature) : Add Github Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [samyakmaitre/eventmint#69]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by samyakmaitre** [comment]
Go ahead!

**Comment by KiranBaliga** [comment]
@samyakmaitre please assign this task to me

**Comment by KiranBaliga** [comment]
@samyakmaitre Please review and action accordingly. Thank you! Please add level1 and gssoc24-ext labels to the PR.
