### ISSUE TITLE
Responsiveness and Alignment Issues .

### ISSUE THREAD

**Issue by Sameeratweb** [samyakmaitre/eventmint#7]
![Screenshot 2024-10-01 192217](https://github.com/user-attachments/assets/a85f3692-ae89-441f-a1cb-97724b5e6b8f)

The movie titles seem to be truncated, which can make them hard to read .This issues can be faced for small Devices so we can work on the responsiveness of it.
Please allow me with labels and issues.

GSSoC'24-Extd | Contributor

**Comment by samyakmaitre** [comment]
Please go ahead

**Comment by samyakmaitre** [comment]
issue resolved already by another PR
