### ISSUE TITLE
Dark-mode light mode toggle button on the navbar

### ISSUE THREAD

**Issue by aditya07389** [samyakmaitre/eventmint#73]
# hey @samyakmaitre 
i was just looking at your website , i must say the project is impressive , although i feel its missing a feature i.e. dark mode , i could add this up for you , so the users can toggle between light mode and dark mode according to their convinience .

# i could add a similar button on the navbar :
![image](https://github.com/user-attachments/assets/7c89e97a-004f-43d4-8679-0b7cf55c3921)

please assign this issue to me .

# please add the labels gssoc extd and hacktoberfest.

Looking forward to hearing from you.

**Comment by samyakmaitre** [comment]
Already assigned under issue #57
