### ISSUE TITLE
Search Optimised

### ISSUE THREAD

**Issue by Monu2114** [samyakmaitre/eventmint#76]
Implementing search function in a better way where users can get auto search options in such way : 
![Screenshot 2024-10-04 110650](https://github.com/user-attachments/assets/a0fd6091-9200-4035-a7b2-3f7df071055f)

**Comment by samyakmaitre** [comment]
Please go ahead and create PR.

**Comment by Monu2114** [comment]
Hey am confused the issue is closed so should I work on it ? Or not ?
