### ISSUE TITLE
Improve the UI of Sign up Page 

### ISSUE THREAD

**Issue by UdaySharmaGitHub** [samyakmaitre/eventmint#78]
- Improve the UI of Sign up Page 
- Some elements get hidden in the Sign up page 
- Please aasign this issue under Hactoberfest or  Hactoberfest2024

![image](https://github.com/user-attachments/assets/e38ff950-f26a-473c-a997-70f2c69fcca9)

**Comment by AliGates915** [comment]
**Alignment Issues:**
1. The form fields and buttons are squeezed together on the mobile version (first image). They need more space between them to look neat.
2. The layout is better on the desktop version (second image), but there’s still room to improve the spacing for a cleaner look.

**Text Visibility:**
1. The placeholder text inside the form fields looks faint, which might make it hard to read. Making it darker would help.

**Button Size:**
1. The red "Create Account" button stands out, which is good. But the "Sign in" link below it is too small. It should be bigger or bolder so users notice it easily.

**Password Icons:**
1. The eye icons for showing/hiding passwords are small. They should be bigger for easier interaction.
2. These are the main issues you can address in the UI.
@UdaySharmaGitHub assign me to this issue.

![screencapture-eventmint-vercel-app-signup-2024-10-06-19_48_18](https://github.com/user-attachments/assets/fcad9c2e-930f-40cd-a6b4-5fb76f5b7121)
![screencapture-eventmint-vercel-app-signup-2024-10-06-19_47_37](https://github.com/user-attachments/assets/55c88095-2138-4c0b-859d-77e77abba23e)

**Comment by samyakmaitre** [comment]
Please go ahead and create PR.
