### ISSUE TITLE
Update In Title of WebPage

### ISSUE THREAD

**Issue by Sameeratweb** [samyakmaitre/eventmint#8]
![Screenshot 2024-10-01 193930](https://github.com/user-attachments/assets/0b9bfaa8-a542-4e73-bebb-1ff2a24f66f8)

Update Needed in WebPage it still has the default text as "React App", we can work with it by updating it with the actual title.
Could you allow me to work?  Please give labels and Issues .

GSSoC'24-Extd | Contributor.

**Comment by Sameeratweb** [comment]
Thankyou very much , I hope you merge It.

**Comment by Sameeratweb** [comment]
what should be title eventmint or bookmyshow?

**Comment by samyakmaitre** [comment]
eventmint


Create PR and I will add labels
