### ISSUE TITLE
Desiging the search bar 

### ISSUE THREAD

**Issue by Rohinipilla** [samyakmaitre/eventmint#80]
![image](https://github.com/user-attachments/assets/af50f6d5-261b-4a45-96f3-e78e0bfbbfc2)
make the search bar border-radius to 8px and add a search icon to it

**Comment by shruti9935** [comment]
Can you assign me the issue. I would like to work on it

**Comment by AkanshaOP** [comment]
PLEASE ASSIGN IT TO ME.

**Comment by samyakmaitre** [comment]
@Rohinipilla please go ahead

**Comment by Rohinipilla** [comment]
> @Rohinipilla please go ahead

Thank you
