### ISSUE TITLE
[BUG]  Header not Sticky while scrolling

### ISSUE THREAD

**Issue by riyaaryan2004** [samyakmaitre/eventmint#9]
### Description

The header in the evermint project does not remain fixed at the top of the viewport while scrolling, leading to a poor user experience. When users scroll down the page, the header disappears, making navigation difficult.

Expected Behavior:
The header should remain sticky at the top of the viewport while scrolling, allowing users to easily access navigation links.

I would like to work on this issue and implement a fix for the sticky header. Please assign this task to me.

### Screenshots

![Screenshot 2024-10-01 200236](https://github.com/user-attachments/assets/44dac108-b748-4527-9b31-78abf4115b59)

### Checklist

- [x]  I have checked the existing issues
- [x]  I have read the [Contributing Guidelines](https://github.com/mdazfar2/Ezyshop/blob/main/CONTRIBUTING.md)
- [x] I'm a GSSoC'24-Extd contributor
- [ ]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue (optional)

**Comment by samyakmaitre** [comment]
Please go ahead.

**Comment by Divyansh2992** [comment]
i want to contribute

**Comment by riyaaryan2004** [comment]
@samyakmaitre Thank You for assigning . I m working on  this issue.

**Comment by samyakmaitre** [comment]
Merged
