### ISSUE TITLE
Make Navbar Responsive for Mobile and Desktop Viewports

### ISSUE THREAD

**Issue by Md-SabbirHosen** [samyakmaitre/eventmint#90]
<img width="319" alt="screencapture-eventmint-vercel-app-2024-10-06-19_04_30" src="https://github.com/user-attachments/assets/9f4b075f-3ce1-44db-8a5e-7fc28321c5e0">

**Description:**

The current navbar is not fully responsive, leading to a suboptimal user experience, especially on mobile devices. Tailwind CSS provides a utility-first approach that can be used to easily create a responsive, mobile-friendly navbar that adapts across different screen sizes.

**Proposed Solution:**
- Use Tailwind CSS utility classes to build a responsive navbar.
- Apply media queries through Tailwind’s built-in responsive breakpoints (`sm`, `md`, `lg`, `xl`) to adjust the layout for different screen sizes.
- Implement a hamburger menu for mobile view.
- Ensure smooth transitions for toggling the mobile menu using `transition` and `duration` classes.
- Maintain consistent styling with Tailwind’s spacing, padding, and margin utilities for a clean look.

**Impact:**
- Seamless navigation across different devices, enhancing mobile usability.
- Improved performance by leveraging Tailwind CSS’s utility-first approach.
- Cleaner, more maintainable codebase through the use of Tailwind classes.

**Additional Request:**
 Please assign this issue to me under the labels ***gssoc24-ex*** and ***hacktoberfest*** as I would like to contribute as part of these events.

**Comment by samyakmaitre** [comment]
Please go ahead @Md-SabbirHosen

**Comment by samyakmaitre** [comment]
issue resolved already by another PR
