### ISSUE TITLE
Feature: Make Logo Clickable to Redirect to Home Page

### ISSUE THREAD

**Issue by Arnab7456** [samyakmaitre/eventmint#92]
Currently, the logo (bookmyshow) is a static element on the page. The expected behavior is for users to click on the logo and be redirected to the home page.
@samyakmaitre  please assign it to me , so I can contribute

**Comment by shruti9935** [comment]
Can you assign me this part.

**Comment by Arnab7456** [comment]
First, I noticed the issue, so I raised the question: why was this assigned to you by the repo mentor? Is there any logic behind it

**Comment by samyakmaitre** [comment]
@Arnab7456  please go ahead
