### ISSUE TITLE
Resource Leakage 

### ISSUE THREAD

**Issue by AngadSudan** [samyakmaitre/eventmint#94]
We usually don't push .env file to the github repo as it is considered leakage of resources.

![image](https://github.com/user-attachments/assets/53af44d6-8bcf-49a0-a8f4-c2581cf8657b)

Possible Fix add .env file to .gitignore and add an .env.sample file insteaed.

**Comment by samyakmaitre** [comment]
please go ahead

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
