### ISSUE TITLE
[Feature Request] 🚀 Update Website Icon from BookMyShow to EventMint 

### ISSUE THREAD

**Issue by iarmaanx** [samyakmaitre/eventmint#95]
![Screenshot 2024-10-06 215714](https://github.com/user-attachments/assets/e052dcee-c765-4bef-9f5c-78a40c92a9e9)

I propose updating the website's current favicon and branding icon from BookMyShow to EventMint to better align with the current project identity and direction. This change will reflect the platform's evolving brand and provide a more distinctive, unique look.

Proposed Changes:
- Favicon Update: Replace the BookMyShow favicon with the new EventMint icon.
- Branding Icon: Ensure the updated icon appears across all instances (browser tab, bookmarks, and mobile app) where the current BookMyShow icon is used.
- File Formats: Upload the new EventMint icon in appropriate formats (.ico, .png) for compatibility across devices and platforms.
- Consistency: Ensure that the new EventMint icon is consistent with the brand guidelines, maintaining high visibility and aesthetic appeal.

Please add the following labels:

gssoc-ext
hacktoberfest-accepted

Please assign this issue to me so I can begin working on it immediately.

**Comment by rohitmore07** [comment]
I'm interested in doing it! Can you assign this to me?

**Comment by samyakmaitre** [comment]
@iarmaanx please go ahead, refer src folder for logos and favicons.

**Comment by iarmaanx** [comment]
Please add the following labels:

gssoc-ext
hacktoberfest-accepted

Please assign this issue to me so I can begin working on it immediately.

**Comment by samyakmaitre** [comment]
Create PR and I will add labels
