### ISSUE TITLE
Create an About Us, Terms of use and Privacy policy pages 

### ISSUE THREAD

**Issue by Devaki01** [samyakmaitre/eventmint#97]
I would love to contribute by creating About Us, Terms of use and Privacy policy pages for eventmint with relevant content ensuring that they match with the theme of the rest of the website. 

Please assign me this issue under gssoc'24 and hacktoberfest.

**Comment by Praneetha-4** [comment]
i would like to change the images of the movie title ,
please assign me this issue!

**Comment by samyakmaitre** [comment]
please go ahead @Devaki01

**Comment by Devaki01** [comment]
> please go ahead @Devaki01

Thank you so much. Will complete it by tomorrow evening. Also, will also please add the labels as well?

**Comment by samyakmaitre** [comment]
once done create PR I will surely add.
